require=(function e(t,n,r){function s(o,u){if(!n[o]){if(!t[o]){var a=typeof require=="function"&&require;if(!u&&a)return a(o,!0);if(i)return i(o,!0);throw new Error("Cannot find module '"+o+"'")}var f=n[o]={exports:{}};t[o][0].call(f.exports,function(e){var n=t[o][1][e];return s(n?n:e)},f,f.exports,e,t,n,r)}return n[o].exports}var i=typeof require=="function"&&require;for(var o=0;o<r.length;o++)s(r[o]);return s})({"r1PLSq":[function(require,module,exports){
var problem;

module.exports = problem = new Problem("\nProblem 1: Multiples of 3 and 5\n-------------------------------\n\nIf we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9.\nThe sum of these multiples is 23.\n\nFind the sum of all the multiples of 3 or 5 below 1000.\n");

problem.run = {
  test: function() {
    var i, sum, _i;
    sum = 0;
    for (i = _i = 1; _i < 10; i = ++_i) {
      if ((i % 3 === 0) || (i % 5 === 0)) {
        sum += i;
      }
    }
    return equal(sum, 23, "Sum of natural numbers < 10: " + sum);
  },
  answer: function() {
    var i, sum, _i;
    sum = 0;
    for (i = _i = 1; _i < 1000; i = ++_i) {
      if ((i % 3 === 0) || (i % 5 === 0)) {
        sum += i;
      }
    }
    return sum;
  }
};


},{}],"e001":[function(require,module,exports){
module.exports=require('r1PLSq');
},{}],"78QEJ9":[function(require,module,exports){
var problem;

module.exports = problem = new Problem("\nProblem 2: Even Fibonacci numbers\n---------------------------------\n\nEach new term in the Fibonacci sequence is generated by adding the previous two terms.\nBy starting with 1 and 2, the first 10 terms will be:\n\n1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...\n\nBy considering the terms in the Fibonacci sequence whose values do not exceed four million,\nfind the sum of the even-valued terms.\n");

problem.run = function() {
  var curr, next, prev, sum;
  prev = 1;
  curr = 1;
  sum = 0;
  while (curr < 4000000) {
    if ((curr % 2) === 0) {
      sum += curr;
    }
    next = curr + prev;
    prev = curr;
    curr = next;
  }
  return sum;
};


},{}],"e002":[function(require,module,exports){
module.exports=require('78QEJ9');
},{}],"HokIVh":[function(require,module,exports){
var isPrime, largestPrimeFactor, leastFactor, primeFactors, problem;

module.exports = problem = new Problem("\nProblem 3: Largest prime factor\n-------------------------------\n\nThe prime factors of 13195 are 5, 7, 13 and 29.\n\nWhat is the largest prime factor of the number 600851475143 ?\n");

leastFactor = function(n) {
  var i, m, _i;
  if (isNaN(n) || !isFinite(n)) {
    return NaN;
  }
  if (n === 0) {
    return 0;
  }
  if ((n % 1) !== 0 || (n * n) < 2) {
    return 1;
  }
  if ((n % 2) === 0) {
    return 2;
  }
  if ((n % 3) === 0) {
    return 3;
  }
  if ((n % 5) === 0) {
    return 5;
  }
  m = Math.sqrt(n);
  for (i = _i = 7; _i <= m; i = _i += 30) {
    if ((n % i) === 0) {
      return i;
    }
    if ((n % (i + 4)) === 0) {
      return i + 4;
    }
    if ((n % (i + 6)) === 0) {
      return i + 6;
    }
    if ((n % (i + 10)) === 0) {
      return i + 10;
    }
    if ((n % (i + 12)) === 0) {
      return i + 12;
    }
    if ((n % (i + 16)) === 0) {
      return i + 16;
    }
    if ((n % (i + 22)) === 0) {
      return i + 22;
    }
    if ((n % (i + 24)) === 0) {
      return i + 24;
    }
  }
  return n;
};

isPrime = function(n) {
  if (isNaN(n) || !isFinite(n) || (n % 1) !== 0 || (n < 2)) {
    return false;
  }
  if (n === leastFactor(n)) {
    return true;
  }
  return false;
};

primeFactors = function(n) {
  var factor, factors;
  if (n === 1) {
    return [1];
  }
  factors = [];
  while (!isPrime(n)) {
    factor = leastFactor(n);
    factors.push(factor);
    n /= factor;
  }
  factors.push(n);
  return factors;
};

largestPrimeFactor = function(n) {
  var factor;
  if (n === 1) {
    return 1;
  }
  while (!isPrime(n)) {
    factor = leastFactor(n);
    n /= factor;
  }
  return n;
};

problem.run = function() {
  return largestPrimeFactor(600851475143);
};


},{}],"e003":[function(require,module,exports){
module.exports=require('HokIVh');
},{}],"e004":[function(require,module,exports){
module.exports=require('ys3VZW');
},{}],"ys3VZW":[function(require,module,exports){
var isPalindrome, problem;

module.exports = problem = new Problem("\nProblem 4: Largest palindrome product\n-------------------------------------\n\nA palindromic number reads the same both ways.\n\nFind the largest palindrome made from the product of two 3-digit numbers.\n");

isPalindrome = function(n) {
  var i, str, _i, _ref;
  str = n.toString();
  for (i = _i = 0, _ref = str.length / 2; 0 <= _ref ? _i < _ref : _i > _ref; i = 0 <= _ref ? ++_i : --_i) {
    if (str[i] !== str[str.length - 1 - i]) {
      return false;
    }
  }
  return true;
};

problem.run = {
  test: function() {
    var v, _i, _j, _len, _len1, _ref, _ref1, _results;
    _ref = [1, 11, 121, 1221, 12321, 1234321];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      v = _ref[_i];
      equal(isPalindrome(v), true, "isPalindrome(" + v + ") returns true");
    }
    _ref1 = [12, 123, 1234, 12345, 123456, 12324];
    _results = [];
    for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
      v = _ref1[_j];
      _results.push(equal(isPalindrome(v), false, "isPalindrome(" + v + ") returns false"));
    }
    return _results;
  },
  answer: function() {
    var i, j, largesti, largestj, largestp, product, _i, _j;
    largesti = 0;
    largestj = 0;
    largestp = 0;
    for (i = _i = 100; _i <= 999; i = ++_i) {
      for (j = _j = 100; _j <= 999; j = ++_j) {
        product = i * j;
        if (isPalindrome(product)) {
          largesti = i;
          largestj = j;
          largestp = product;
        }
      }
    }
    return largestp;
  }
};


},{}],"e005":[function(require,module,exports){
module.exports=require('8Y1Hkt');
},{}],"8Y1Hkt":[function(require,module,exports){
var problem;

module.exports = problem = new Problem("\nProblem 5: Smallest multiple\n----------------------------\n\n2520 is the smallest number that can be divided by each of the numbers from 1 to 10 without any remainder.\n\nWhat is the smallest positive number that is evenly divisible by all of the numbers from 1 to 20?\n");

problem.run = function() {
  var found, i, n, _i;
  n = 0;
  while (true) {
    n += 20;
    found = true;
    for (i = _i = 1; _i <= 20; i = ++_i) {
      if ((n % i) !== 0) {
        found = false;
        break;
      }
    }
    if (found) {
      break;
    }
  }
  return n;
};


},{}],"e006":[function(require,module,exports){
module.exports=require('a5iprt');
},{}],"a5iprt":[function(require,module,exports){
var differenceSumSquares, problem, squareOfSum, sumOfSquares;

module.exports = problem = new Problem("\nProblem 6: Sum square difference\n--------------------------------\n\nThe sum of the squares of the first ten natural numbers is,\n\n             1^2 + 2^2 + ... + 10^2 = 385\n\nThe square of the sum of the first ten natural numbers is,\n\n          (1 + 2 + ... + 10)^2 = 55^2 = 3025\n\nHence the difference between the sum of the squares of the first ten natural numbers and the square of the sum is 3025 − 385 = 2640.\n\nFind the difference between the sum of the squares of the first one hundred natural numbers and the square of the sum.\n");

sumOfSquares = function(n) {
  var i, sum, _i;
  sum = 0;
  for (i = _i = 1; 1 <= n ? _i <= n : _i >= n; i = 1 <= n ? ++_i : --_i) {
    sum += i * i;
  }
  return sum;
};

squareOfSum = function(n) {
  var i, sum, _i;
  sum = 0;
  for (i = _i = 1; 1 <= n ? _i <= n : _i >= n; i = 1 <= n ? ++_i : --_i) {
    sum += i;
  }
  return sum * sum;
};

differenceSumSquares = function(n) {
  return squareOfSum(n) - sumOfSquares(n);
};

problem.run = {
  test: function() {
    equal(sumOfSquares(10), 385, "Sum of squares of first ten natural numbers is 385");
    equal(squareOfSum(10), 3025, "Square of sum of first ten natural numbers is 3025");
    return equal(differenceSumSquares(10), 2640, "Difference in values for the first ten natural numbers is 2640");
  },
  answer: function() {
    return differenceSumSquares(100);
  }
};


},{}],"e007":[function(require,module,exports){
module.exports=require('v+s2Qb');
},{}],"v+s2Qb":[function(require,module,exports){
var nthPrime, problem;

module.exports = problem = new Problem("\nProblem 7: 10001st prime\n------------------------\n\nBy listing the first six prime numbers: 2, 3, 5, 7, 11, and 13, we can see that the 6th prime is 13.\n\nWhat is the 10,001st prime number?\n");

nthPrime = function(n) {
  var i, sieve, _i;
  sieve = new IncrementalSieve;
  for (i = _i = 1; 1 <= n ? _i < n : _i > n; i = 1 <= n ? ++_i : --_i) {
    sieve.next();
  }
  return sieve.next();
};

problem.run = {
  test: function() {
    return equal(nthPrime(6), 13, "6th prime is 13");
  },
  answer: function() {
    return nthPrime(10001);
  }
};


},{}],"e008":[function(require,module,exports){
module.exports=require('4902rv');
},{}],"4902rv":[function(require,module,exports){
var digit, digits, largestProduct, problem, str;

module.exports = problem = new Problem("\nProblem 8: Largest product in a series\n--------------------------------------\n\nThe four adjacent digits in the 1000-digit number that have the greatest product are 9 x 9 x 8 x 9 = 5832.\n\n  73167176531330624919225119674426574742355349194934\n  96983520312774506326239578318016984801869478851843\n  85861560789112949495459501737958331952853208805511\n  12540698747158523863050715693290963295227443043557\n  66896648950445244523161731856403098711121722383113\n  62229893423380308135336276614282806444486645238749\n  30358907296290491560440772390713810515859307960866\n  70172427121883998797908792274921901699720888093776\n  65727333001053367881220235421809751254540594752243\n  52584907711670556013604839586446706324415722155397\n  53697817977846174064955149290862569321978468622482\n  83972241375657056057490261407972968652414535100474\n  82166370484403199890008895243450658541227588666881\n  16427171479924442928230863465674813919123162824586\n  17866458359124566529476545682848912883142607690042\n  24219022671055626321111109370544217506941658960408\n  07198403850962455444362981230987879927244284909188\n  84580156166097919133875499200524063689912560717606\n  05886116467109405077541002256983155200055935729725\n  71636269561882670428252483600823257530420752963450\n\nFind the thirteen adjacent digits in the 1000-digit number that have the greatest product. What is the value of this product?\n");

str = "73167176531330624919225119674426574742355349194934\n96983520312774506326239578318016984801869478851843\n85861560789112949495459501737958331952853208805511\n12540698747158523863050715693290963295227443043557\n66896648950445244523161731856403098711121722383113\n62229893423380308135336276614282806444486645238749\n30358907296290491560440772390713810515859307960866\n70172427121883998797908792274921901699720888093776\n65727333001053367881220235421809751254540594752243\n52584907711670556013604839586446706324415722155397\n53697817977846174064955149290862569321978468622482\n83972241375657056057490261407972968652414535100474\n82166370484403199890008895243450658541227588666881\n16427171479924442928230863465674813919123162824586\n17866458359124566529476545682848912883142607690042\n24219022671055626321111109370544217506941658960408\n07198403850962455444362981230987879927244284909188\n84580156166097919133875499200524063689912560717606\n05886116467109405077541002256983155200055935729725\n71636269561882670428252483600823257530420752963450";

str = str.replace(/[^0-9]/gm, "");

digits = (function() {
  var _i, _len, _results;
  _results = [];
  for (_i = 0, _len = str.length; _i < _len; _i++) {
    digit = str[_i];
    _results.push(parseInt(digit));
  }
  return _results;
})();

largestProduct = function(digitCount) {
  var end, i, largest, product, start, _i, _j, _ref;
  if (digitCount > digits.length) {
    return 0;
  }
  largest = 0;
  for (start = _i = 0, _ref = digits.length - digitCount; 0 <= _ref ? _i <= _ref : _i >= _ref; start = 0 <= _ref ? ++_i : --_i) {
    end = start + digitCount;
    product = 1;
    for (i = _j = start; start <= end ? _j < end : _j > end; i = start <= end ? ++_j : --_j) {
      product *= digits[i];
    }
    if (largest < product) {
      largest = product;
    }
  }
  return largest;
};

problem.run = {
  test: function() {
    return equal(largestProduct(4), 5832, "Greatest product of 4 adjacent digits is 5832");
  },
  answer: function() {
    return largestProduct(13);
  }
};


},{}],"e009":[function(require,module,exports){
module.exports=require('w1omiu');
},{}],"w1omiu":[function(require,module,exports){
var findFirstTriplet, isTriplet, problem;

module.exports = problem = new Problem("\nProblem 9: Special Pythagorean triplet\n--------------------------------------\n\nA Pythagorean triplet is a set of three natural numbers, a < b < c, for which,\n\n    a^2 + b^2 = c^2\n\nFor example, 3^2 + 4^2 = 9 + 16 = 25 = 5^2.\n\nThere exists exactly one Pythagorean triplet for which a + b + c = 1000.\n\nFind the product abc.\n");

isTriplet = function(a, b, c) {
  return ((a * a) + (b * b)) === (c * c);
};

findFirstTriplet = function(sum) {
  var a, b, c, _i, _j;
  for (a = _i = 1; _i < 1000; a = ++_i) {
    for (b = _j = 1; _j < 1000; b = ++_j) {
      c = 1000 - a - b;
      if (isTriplet(a, b, c)) {
        return [a, b, c];
      }
    }
  }
  return false;
};

problem.run = {
  test: function() {
    return equal(isTriplet(3, 4, 5), true, "(3,4,5) is a Pythagorean triplet");
  },
  answer: function() {
    return findFirstTriplet(1000);
  }
};


},{}],"VGQJ6S":[function(require,module,exports){
var primeSum, problem;

module.exports = problem = new Problem("\nProblem 10: Summation of primes\n-------------------------------\n\nThe sum of the primes below 10 is 2 + 3 + 5 + 7 = 17.\n\nFind the sum of all the primes below two million.\n");

primeSum = function(ceiling) {
  var n, sieve, sum;
  sieve = new IncrementalSieve;
  sum = 0;
  while (true) {
    n = sieve.next();
    if (n >= ceiling) {
      break;
    }
    sum += n;
  }
  return sum;
};

problem.run = {
  test: function() {
    return equal(primeSum(10), 17, "Sum of primes below 10 is 17");
  },
  answer: function() {
    return primeSum(2000000);
  }
};


},{}],"e010":[function(require,module,exports){
module.exports=require('VGQJ6S');
},{}],"e011":[function(require,module,exports){
module.exports=require('vx/pw5');
},{}],"vx/pw5":[function(require,module,exports){
var digit, digits, getLine, getLineProduct, grid, i, index, j, problem, rawDigits, _i, _j, _k;

module.exports = problem = new Problem("\nProblem 11: Largest product in a grid\n-------------------------------------\n\nIn the 20x20 grid below, four numbers along a diagonal line have been marked in red.\n\n          08 02 22 97 38 15 00 40 00 75 04 05 07 78 52 12 50 77 91 08\n          49 49 99 40 17 81 18 57 60 87 17 40 98 43 69 48 04 56 62 00\n          81 49 31 73 55 79 14 29 93 71 40 67 53 88 30 03 49 13 36 65\n          52 70 95 23 04 60 11 42 69 24 68 56 01 32 56 71 37 02 36 91\n          22 31 16 71 51 67 63 89 41 92 36 54 22 40 40 28 66 33 13 80\n          24 47 32 60 99 03 45 02 44 75 33 53 78 36 84 20 35 17 12 50\n          32 98 81 28 64 23 67 10 26_38 40 67 59 54 70 66 18 38 64 70\n          67 26 20 68 02 62 12 20 95 63_94 39 63 08 40 91 66 49 94 21\n          24 55 58 05 66 73 99 26 97 17 78_78 96 83 14 88 34 89 63 72\n          21 36 23 09 75 00 76 44 20 45 35 14 00 61 33 97 34 31 33 95\n          78 17 53 28 22 75 31 67 15 94 03 80 04 62 16 14 09 53 56 92\n          16 39 05 42 96 35 31 47 55 58 88 24 00 17 54 24 36 29 85 57\n          86 56 00 48 35 71 89 07 05 44 44 37 44 60 21 58 51 54 17 58\n          19 80 81 68 05 94 47 69 28 73 92 13 86 52 17 77 04 89 55 40\n          04 52 08 83 97 35 99 16 07 97 57 32 16 26 26 79 33 27 98 66\n          88 36 68 87 57 62 20 72 03 46 33 67 46 55 12 32 63 93 53 69\n          04 42 16 73 38 25 39 11 24 94 72 18 08 46 29 32 40 62 76 36\n          20 69 36 41 72 30 23 88 34 62 99 69 82 67 59 85 74 04 36 16\n          20 73 35 29 78 31 90 01 74 31 49 71 48 86 81 16 23 57 05 54\n          01 70 54 71 83 51 54 69 16 92 33 48 61 43 52 01 89 19 67 48\n\nThe product of these numbers is 26 x 63 x 78 x 14 = 1788696.\n\nWhat is the greatest product of four adjacent numbers in the same direction (up, down, left, right, or diagonally) in the 20x20 grid?\n");

rawDigits = "08 02 22 97 38 15 00 40 00 75 04 05 07 78 52 12 50 77 91 08\n49 49 99 40 17 81 18 57 60 87 17 40 98 43 69 48 04 56 62 00\n81 49 31 73 55 79 14 29 93 71 40 67 53 88 30 03 49 13 36 65\n52 70 95 23 04 60 11 42 69 24 68 56 01 32 56 71 37 02 36 91\n22 31 16 71 51 67 63 89 41 92 36 54 22 40 40 28 66 33 13 80\n24 47 32 60 99 03 45 02 44 75 33 53 78 36 84 20 35 17 12 50\n32 98 81 28 64 23 67 10 26 38 40 67 59 54 70 66 18 38 64 70\n67 26 20 68 02 62 12 20 95 63 94 39 63 08 40 91 66 49 94 21\n24 55 58 05 66 73 99 26 97 17 78 78 96 83 14 88 34 89 63 72\n21 36 23 09 75 00 76 44 20 45 35 14 00 61 33 97 34 31 33 95\n78 17 53 28 22 75 31 67 15 94 03 80 04 62 16 14 09 53 56 92\n16 39 05 42 96 35 31 47 55 58 88 24 00 17 54 24 36 29 85 57\n86 56 00 48 35 71 89 07 05 44 44 37 44 60 21 58 51 54 17 58\n19 80 81 68 05 94 47 69 28 73 92 13 86 52 17 77 04 89 55 40\n04 52 08 83 97 35 99 16 07 97 57 32 16 26 26 79 33 27 98 66\n88 36 68 87 57 62 20 72 03 46 33 67 46 55 12 32 63 93 53 69\n04 42 16 73 38 25 39 11 24 94 72 18 08 46 29 32 40 62 76 36\n20 69 36 41 72 30 23 88 34 62 99 69 82 67 59 85 74 04 36 16\n20 73 35 29 78 31 90 01 74 31 49 71 48 86 81 16 23 57 05 54\n01 70 54 71 83 51 54 69 16 92 33 48 61 43 52 01 89 19 67 48".replace(/[^0-9 ]/gm, " ");

digits = (function() {
  var _i, _len, _ref, _results;
  _ref = rawDigits.split(" ");
  _results = [];
  for (_i = 0, _len = _ref.length; _i < _len; _i++) {
    digit = _ref[_i];
    _results.push(parseInt(digit));
  }
  return _results;
})();

grid = Array(20);

for (i = _i = 0; _i < 20; i = ++_i) {
  grid[i] = Array(20);
}

index = 0;

for (j = _j = 0; _j < 20; j = ++_j) {
  for (i = _k = 0; _k < 20; i = ++_k) {
    grid[i][j] = digits[index];
    index++;
  }
}

getLineProduct = function(sx, sy, dx, dy) {
  var ex, ey, product, x, y, _l;
  ex = sx + (4 * dx);
  if ((ex < 0) || (ex >= 20)) {
    return -1;
  }
  ey = sy + (4 * dy);
  if ((ey < 0) || (ey >= 20)) {
    return -1;
  }
  x = sx;
  y = sy;
  product = 1;
  for (i = _l = 0; _l < 4; i = ++_l) {
    product *= grid[x][y];
    x += dx;
    y += dy;
  }
  return product;
};

getLine = function(sx, sy, dx, dy) {
  var ex, ey, line, x, y, _l;
  ex = sx + (4 * dx);
  if ((ex < 0) || (ex >= 20)) {
    return [];
  }
  ey = sy + (4 * dy);
  if ((ey < 0) || (ey >= 20)) {
    return [];
  }
  line = [];
  x = sx;
  y = sy;
  for (i = _l = 0; _l < 4; i = ++_l) {
    line.push(grid[x][y]);
    x += dx;
    y += dy;
  }
  return line;
};

problem.run = {
  test: function() {
    ok(true, JSON.stringify(getLine(8, 6, 1, 1)));
    equal(getLineProduct(8, 6, 1, 1), 1788696, "Diagonal value shown in example equals 1,788,696");
    equal(getLineProduct(4, 8, 1, 0), 48477312, "Correct answer is right of (4,8) and has values []");
    return ok(true, JSON.stringify(getLine(4, 8, 1, 0)));
  },
  answer: function() {
    var max, p, q, _l, _m;
    max = {
      product: 1,
      i: 0,
      j: 0,
      dir: "right"
    };
    for (j = _l = 0; _l < 20; j = ++_l) {
      for (i = _m = 0; _m < 20; i = ++_m) {
        p = getLineProduct(i, j, 1, 0);
        if (max.product < p) {
          max.product = p;
          max.i = i;
          max.j = j;
          max.dir = "right";
          if (p === 48477312) {
            console.log("wat");
            q = getLineProduct(i, j, 1, 0);
            console.log(q);
          }
        }
        p = getLineProduct(i, j, 0, 1);
        if (max.product < p) {
          max.product = p;
          max.i = i;
          max.j = j;
          max.dir = "down";
        }
        p = getLineProduct(i, j, 1, 1);
        if (max.product < p) {
          max.product = p;
          max.i = i;
          max.j = j;
          max.dir = "diagonal";
        }
      }
    }
    return max;
  }
};


},{}],"shared":[function(require,module,exports){
module.exports=require('FiNUfl');
},{}],"FiNUfl":[function(require,module,exports){
var IncrementalSieve, root;

root = window;

IncrementalSieve = (function() {
  function IncrementalSieve() {
    this.n = 0;
  }

  IncrementalSieve.prototype.next = function() {
    var nxt, p2, s;
    this.n += 2;
    if (this.n < 7) {
      if (this.n < 3) {
        this.n = 1;
        return 2;
      }
      if (this.n < 5) {
        return 3;
      }
      this.dict = {};
      this.bps = new IncrementalSieve();
      this.bps.next();
      this.p = this.bps.next();
      this.q = this.p * this.p;
      return 5;
    } else {
      s = this.dict[this.n];
      if (!s) {
        if (this.n < this.q) {
          return this.n;
        } else {
          p2 = this.p << 1;
          this.dict[this.n + p2] = p2;
          this.p = this.bps.next();
          this.q = this.p * this.p;
          return this.next();
        }
      } else {
        delete this.dict[this.n];
        nxt = this.n + s;
        while (this.dict[nxt]) {
          nxt += s;
        }
        this.dict[nxt] = s;
        return this.next();
      }
    }
  };

  return IncrementalSieve;

})();

root.IncrementalSieve = IncrementalSieve;


},{}],"Vazq8s":[function(require,module,exports){
var LAST_PROBLEM, Problem, root;

LAST_PROBLEM = 11;

root = window;

root.escapedStringify = function(o) {
  var str;
  str = JSON.stringify(o);
  str = str.replace("]", "\\]");
  return str;
};

root.runAll = function() {
  var lastPuzzle, loadNextScript, nextIndex;
  lastPuzzle = LAST_PROBLEM;
  nextIndex = 0;
  loadNextScript = function() {
    if (nextIndex < lastPuzzle) {
      nextIndex++;
      return runTest(nextIndex, loadNextScript);
    }
  };
  return loadNextScript();
};

root.iterateProblems = function(args) {
  var indexToProcess, iterateNext;
  indexToProcess = null;
  if (args.endIndex > 0) {
    if (args.startIndex <= args.endIndex) {
      indexToProcess = args.startIndex;
      args.startIndex++;
    }
  } else {
    if (args.list.length > 0) {
      indexToProcess = args.list.shift();
    }
  }
  if (indexToProcess !== null) {
    iterateNext = function() {
      window.args = args;
      return runTest(indexToProcess, function() {
        return iterateProblems(args);
      });
    };
    return iterateNext();
  }
};

root.runTest = function(index, cb) {
  var moduleName, problem;
  moduleName = "e" + (('000' + index).slice(-3));
  window.index = index;
  problem = require(moduleName);
  problem.process();
  if (cb) {
    return window.setTimeout(cb, 0);
  }
};

Problem = (function() {
  function Problem(description) {
    var lines;
    this.description = description;
    this.index = window.index;
    lines = this.description.split(/\n/);
    while (lines.length > 0 && lines[0].length === 0) {
      lines.shift();
    }
    this.title = lines.shift();
    this.line = lines.shift();
    this.description = lines.join("\n");
  }

  Problem.prototype.now = function() {
    if (window.performance) {
      return window.performance.now();
    } else {
      return new Date().getTime();
    }
  };

  Problem.prototype.process = function() {
    var answer, answerFunc, end, formattedTitle, ms, start, testFunc;
    if (window.args.description) {
      window.terminal.echo("[[;#444444;]_______________________________________________________________________________________________]\n");
    }
    formattedTitle = $.terminal.format("[[;#ffaa00;]" + this.title + "]");
    window.terminal.echo("<a href=\"?c=" + window.args.cmd + "%20" + this.index + "\">" + formattedTitle + "</a>", {
      raw: true
    });
    if (window.args.description) {
      window.terminal.echo("[[;#444444;]" + this.line + "]");
      window.terminal.echo("[[;#ccccee;]" + this.description + "]\n");
    }
    if (this.run.hasOwnProperty('test')) {
      answerFunc = this.run.answer;
      testFunc = this.run.test;
    } else {
      answerFunc = this.run;
      testFunc = void 0;
    }
    if (window.args.test) {
      if (testFunc === void 0) {
        window.terminal.echo("[[;#444444;] (no tests)]");
      } else {
        testFunc();
      }
    }
    if (window.args.answer) {
      start = this.now();
      answer = answerFunc();
      end = this.now();
      ms = end - start;
      return window.terminal.echo("[[;#ffffff;] -> ][[;#aaffaa;]Answer:] ([[;#aaffff;]" + (ms.toFixed(1)) + "ms]): [[;#ffffff;]" + (escapedStringify(answer)) + "]");
    }
  };

  return Problem;

})();

root.Problem = Problem;

root.ok = function(v, msg) {
  return window.terminal.echo("[[;#ffffff;] *  ]" + v + ": " + msg);
};

root.equal = function(a, b, msg) {
  if (a === b) {
    return window.terminal.echo("[[;#ffffff;] *  ][[;#555555;]PASS: " + msg + "]");
  } else {
    return window.terminal.echo("[[;#ffffff;] *  ][[;#ffaaaa;]FAIL: " + msg + " (" + a + " != " + b + ")]");
  }
};

root.onCommand = (function(_this) {
  return function(command) {
    var arg, args, cmd, process, v, verbose, _i, _len, _ref;
    if (command.length === 0) {
      return;
    }
    cmd = $.terminal.parseCommand(command);
    if (cmd.name.length === 0) {
      return;
    }
    console.log(cmd);
    verbose = false;
    args = {
      startIndex: 0,
      endIndex: 0,
      list: [],
      description: false,
      test: false,
      answer: false
    };
    process = true;
    _ref = cmd.args;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      arg = _ref[_i];
      arg = String(arg);
      if (arg.length < 1) {
        continue;
      }
      if (arg[0] === 'v') {
        verbose = true;
      } else if (arg.match(/^\d+$/)) {
        v = parseInt(arg);
        if ((v >= 1) && (v <= LAST_PROBLEM)) {
          args.list.push(v);
        } else {
          process = false;
          window.terminal.echo("[[;#ffaaaa;]No such test: " + v + " (valid tests 1-" + LAST_PROBLEM + ")]");
        }
      }
    }
    if (args.list.length === 0) {
      args.startIndex = 1;
      args.endIndex = LAST_PROBLEM;
    }
    if (cmd.name[0] === 'l') {
      args.cmd = "list";
    } else if (cmd.name[0] === 'd') {
      args.cmd = "describe";
      args.description = true;
    } else if (cmd.name[0] === 't') {
      args.cmd = "test";
      args.test = true;
    } else if (cmd.name[0] === 'a') {
      args.cmd = "answer";
      args.answer = true;
    } else if (cmd.name[0] === 'r') {
      args.cmd = "run";
      args.test = true;
      args.answer = true;
    } else if (cmd.name[0] === 'd') {
      args.cmd = "describe";
      args.description = true;
    } else if (cmd.name[0] === 'h') {
      args.cmd = "help";
      process = false;
      window.terminal.echo("Commands:\n\n    list [X]     - List problem titles\n    describe [X] - Display full problem descriptions\n    test [X]     - Run unit tests\n    answer [X]   - Time and calculate answer\n    run [X]      - test and answer combined\n    help         - This help\n\n    In all of these, [X] can be a list of one or more problem numbers. (a value from 1 to " + LAST_PROBLEM + "). If absent, it implies all problems.\n    Also, adding the word \"verbose\" to some of these commands will emit the description before performing the task.\n");
    } else {
      process = false;
      window.terminal.echo("[[;#ffaaaa;]Unknown command.]");
    }
    if (verbose) {
      args.description = true;
    }
    if (process) {
      return iterateProblems(args);
    }
  };
})(this);


},{}],"terminal":[function(require,module,exports){
module.exports=require('Vazq8s');
},{}]},{},[])
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiZ2VuZXJhdGVkLmpzIiwic291cmNlcyI6WyIuLlxcbm9kZV9tb2R1bGVzXFxicm93c2VyaWZ5XFxub2RlX21vZHVsZXNcXGJyb3dzZXItcGFja1xcX3ByZWx1ZGUuanMiLCIuLlxcc3JjXFxlMDAxLmNvZmZlZSIsIi4uXFxzcmNcXGUwMDIuY29mZmVlIiwiLi5cXHNyY1xcZTAwMy5jb2ZmZWUiLCIuLlxcc3JjXFxlMDA0LmNvZmZlZSIsIi4uXFxzcmNcXGUwMDUuY29mZmVlIiwiLi5cXHNyY1xcZTAwNi5jb2ZmZWUiLCIuLlxcc3JjXFxlMDA3LmNvZmZlZSIsIi4uXFxzcmNcXGUwMDguY29mZmVlIiwiLi5cXHNyY1xcZTAwOS5jb2ZmZWUiLCIuLlxcc3JjXFxlMDEwLmNvZmZlZSIsIi4uXFxzcmNcXGUwMTEuY29mZmVlIiwiLi5cXHNyY1xcc2hhcmVkLmNvZmZlZSIsIi4uXFxzcmNcXHRlcm1pbmFsLmNvZmZlZSJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiQUFBQTtBQ0FBLElBQUEsT0FBQTs7QUFBQSxNQUFNLENBQUMsT0FBUCxHQUFpQixPQUFBLEdBQWMsSUFBQSxPQUFBLENBQVEsdVFBQVIsQ0FBL0IsQ0FBQTs7QUFBQSxPQVlPLENBQUMsR0FBUixHQUNFO0FBQUEsRUFBQSxJQUFBLEVBQU0sU0FBQSxHQUFBO0FBQ0osUUFBQSxVQUFBO0FBQUEsSUFBQSxHQUFBLEdBQU0sQ0FBTixDQUFBO0FBQ0EsU0FBUyw2QkFBVCxHQUFBO0FBQ0UsTUFBQSxJQUFHLENBQUMsQ0FBQSxHQUFJLENBQUosS0FBUyxDQUFWLENBQUEsSUFBZ0IsQ0FBQyxDQUFBLEdBQUksQ0FBSixLQUFTLENBQVYsQ0FBbkI7QUFDRSxRQUFBLEdBQUEsSUFBTyxDQUFQLENBREY7T0FERjtBQUFBLEtBREE7V0FJQSxLQUFBLENBQU0sR0FBTixFQUFXLEVBQVgsRUFBZ0IsK0JBQUEsR0FBOEIsR0FBOUMsRUFMSTtFQUFBLENBQU47QUFBQSxFQU9BLE1BQUEsRUFBUSxTQUFBLEdBQUE7QUFDTixRQUFBLFVBQUE7QUFBQSxJQUFBLEdBQUEsR0FBTSxDQUFOLENBQUE7QUFDQSxTQUFTLCtCQUFULEdBQUE7QUFDRSxNQUFBLElBQUcsQ0FBQyxDQUFBLEdBQUksQ0FBSixLQUFTLENBQVYsQ0FBQSxJQUFnQixDQUFDLENBQUEsR0FBSSxDQUFKLEtBQVMsQ0FBVixDQUFuQjtBQUNFLFFBQUEsR0FBQSxJQUFPLENBQVAsQ0FERjtPQURGO0FBQUEsS0FEQTtBQUtBLFdBQU8sR0FBUCxDQU5NO0VBQUEsQ0FQUjtDQWJGLENBQUE7Ozs7OztBQ0FBLElBQUEsT0FBQTs7QUFBQSxNQUFNLENBQUMsT0FBUCxHQUFpQixPQUFBLEdBQWMsSUFBQSxPQUFBLENBQVEsNFlBQVIsQ0FBL0IsQ0FBQTs7QUFBQSxPQWVPLENBQUMsR0FBUixHQUFjLFNBQUEsR0FBQTtBQUVaLE1BQUEscUJBQUE7QUFBQSxFQUFBLElBQUEsR0FBTyxDQUFQLENBQUE7QUFBQSxFQUNBLElBQUEsR0FBTyxDQURQLENBQUE7QUFBQSxFQUVBLEdBQUEsR0FBTSxDQUZOLENBQUE7QUFJQSxTQUFNLElBQUEsR0FBTyxPQUFiLEdBQUE7QUFDRSxJQUFBLElBQUcsQ0FBQyxJQUFBLEdBQU8sQ0FBUixDQUFBLEtBQWMsQ0FBakI7QUFDRSxNQUFBLEdBQUEsSUFBTyxJQUFQLENBREY7S0FBQTtBQUFBLElBR0EsSUFBQSxHQUFPLElBQUEsR0FBTyxJQUhkLENBQUE7QUFBQSxJQUlBLElBQUEsR0FBTyxJQUpQLENBQUE7QUFBQSxJQUtBLElBQUEsR0FBTyxJQUxQLENBREY7RUFBQSxDQUpBO0FBWUEsU0FBTyxHQUFQLENBZFk7QUFBQSxDQWZkLENBQUE7Ozs7OztBQ0FBLElBQUEsK0RBQUE7O0FBQUEsTUFBTSxDQUFDLE9BQVAsR0FBaUIsT0FBQSxHQUFjLElBQUEsT0FBQSxDQUFRLDBMQUFSLENBQS9CLENBQUE7O0FBQUEsV0FjQSxHQUFjLFNBQUMsQ0FBRCxHQUFBO0FBQ1osTUFBQSxRQUFBO0FBQUEsRUFBQSxJQUFjLEtBQUEsQ0FBTSxDQUFOLENBQUEsSUFBWSxDQUFBLFFBQUksQ0FBUyxDQUFULENBQTlCO0FBQUEsV0FBTyxHQUFQLENBQUE7R0FBQTtBQUNBLEVBQUEsSUFBWSxDQUFBLEtBQUssQ0FBakI7QUFBQSxXQUFPLENBQVAsQ0FBQTtHQURBO0FBRUEsRUFBQSxJQUFZLENBQUMsQ0FBQSxHQUFJLENBQUwsQ0FBQSxLQUFXLENBQVgsSUFBZ0IsQ0FBQyxDQUFBLEdBQUksQ0FBTCxDQUFBLEdBQVUsQ0FBdEM7QUFBQSxXQUFPLENBQVAsQ0FBQTtHQUZBO0FBR0EsRUFBQSxJQUFZLENBQUMsQ0FBQSxHQUFJLENBQUwsQ0FBQSxLQUFXLENBQXZCO0FBQUEsV0FBTyxDQUFQLENBQUE7R0FIQTtBQUlBLEVBQUEsSUFBWSxDQUFDLENBQUEsR0FBSSxDQUFMLENBQUEsS0FBVyxDQUF2QjtBQUFBLFdBQU8sQ0FBUCxDQUFBO0dBSkE7QUFLQSxFQUFBLElBQVksQ0FBQyxDQUFBLEdBQUksQ0FBTCxDQUFBLEtBQVcsQ0FBdkI7QUFBQSxXQUFPLENBQVAsQ0FBQTtHQUxBO0FBQUEsRUFPQSxDQUFBLEdBQUksSUFBSSxDQUFDLElBQUwsQ0FBVSxDQUFWLENBUEosQ0FBQTtBQVFBLE9BQVMsaUNBQVQsR0FBQTtBQUNFLElBQUEsSUFBZSxDQUFDLENBQUEsR0FBSSxDQUFMLENBQUEsS0FBZ0IsQ0FBL0I7QUFBQSxhQUFPLENBQVAsQ0FBQTtLQUFBO0FBQ0EsSUFBQSxJQUFlLENBQUMsQ0FBQSxHQUFJLENBQUMsQ0FBQSxHQUFFLENBQUgsQ0FBTCxDQUFBLEtBQWdCLENBQS9CO0FBQUEsYUFBTyxDQUFBLEdBQUUsQ0FBVCxDQUFBO0tBREE7QUFFQSxJQUFBLElBQWUsQ0FBQyxDQUFBLEdBQUksQ0FBQyxDQUFBLEdBQUUsQ0FBSCxDQUFMLENBQUEsS0FBZ0IsQ0FBL0I7QUFBQSxhQUFPLENBQUEsR0FBRSxDQUFULENBQUE7S0FGQTtBQUdBLElBQUEsSUFBZSxDQUFDLENBQUEsR0FBSSxDQUFDLENBQUEsR0FBRSxFQUFILENBQUwsQ0FBQSxLQUFnQixDQUEvQjtBQUFBLGFBQU8sQ0FBQSxHQUFFLEVBQVQsQ0FBQTtLQUhBO0FBSUEsSUFBQSxJQUFlLENBQUMsQ0FBQSxHQUFJLENBQUMsQ0FBQSxHQUFFLEVBQUgsQ0FBTCxDQUFBLEtBQWdCLENBQS9CO0FBQUEsYUFBTyxDQUFBLEdBQUUsRUFBVCxDQUFBO0tBSkE7QUFLQSxJQUFBLElBQWUsQ0FBQyxDQUFBLEdBQUksQ0FBQyxDQUFBLEdBQUUsRUFBSCxDQUFMLENBQUEsS0FBZ0IsQ0FBL0I7QUFBQSxhQUFPLENBQUEsR0FBRSxFQUFULENBQUE7S0FMQTtBQU1BLElBQUEsSUFBZSxDQUFDLENBQUEsR0FBSSxDQUFDLENBQUEsR0FBRSxFQUFILENBQUwsQ0FBQSxLQUFnQixDQUEvQjtBQUFBLGFBQU8sQ0FBQSxHQUFFLEVBQVQsQ0FBQTtLQU5BO0FBT0EsSUFBQSxJQUFlLENBQUMsQ0FBQSxHQUFJLENBQUMsQ0FBQSxHQUFFLEVBQUgsQ0FBTCxDQUFBLEtBQWdCLENBQS9CO0FBQUEsYUFBTyxDQUFBLEdBQUUsRUFBVCxDQUFBO0tBUkY7QUFBQSxHQVJBO0FBa0JBLFNBQU8sQ0FBUCxDQW5CWTtBQUFBLENBZGQsQ0FBQTs7QUFBQSxPQW1DQSxHQUFVLFNBQUMsQ0FBRCxHQUFBO0FBQ1IsRUFBQSxJQUFHLEtBQUEsQ0FBTSxDQUFOLENBQUEsSUFBWSxDQUFBLFFBQUksQ0FBUyxDQUFULENBQWhCLElBQStCLENBQUMsQ0FBQSxHQUFJLENBQUwsQ0FBQSxLQUFXLENBQTFDLElBQStDLENBQUMsQ0FBQSxHQUFJLENBQUwsQ0FBbEQ7QUFDRSxXQUFPLEtBQVAsQ0FERjtHQUFBO0FBRUEsRUFBQSxJQUFHLENBQUEsS0FBSyxXQUFBLENBQVksQ0FBWixDQUFSO0FBQ0UsV0FBTyxJQUFQLENBREY7R0FGQTtBQUtBLFNBQU8sS0FBUCxDQU5RO0FBQUEsQ0FuQ1YsQ0FBQTs7QUFBQSxZQTZDQSxHQUFlLFNBQUMsQ0FBRCxHQUFBO0FBQ2IsTUFBQSxlQUFBO0FBQUEsRUFBQSxJQUFjLENBQUEsS0FBSyxDQUFuQjtBQUFBLFdBQU8sQ0FBQyxDQUFELENBQVAsQ0FBQTtHQUFBO0FBQUEsRUFFQSxPQUFBLEdBQVUsRUFGVixDQUFBO0FBR0EsU0FBTSxDQUFBLE9BQUksQ0FBUSxDQUFSLENBQVYsR0FBQTtBQUNFLElBQUEsTUFBQSxHQUFTLFdBQUEsQ0FBWSxDQUFaLENBQVQsQ0FBQTtBQUFBLElBQ0EsT0FBTyxDQUFDLElBQVIsQ0FBYSxNQUFiLENBREEsQ0FBQTtBQUFBLElBRUEsQ0FBQSxJQUFLLE1BRkwsQ0FERjtFQUFBLENBSEE7QUFBQSxFQU9BLE9BQU8sQ0FBQyxJQUFSLENBQWEsQ0FBYixDQVBBLENBQUE7QUFRQSxTQUFPLE9BQVAsQ0FUYTtBQUFBLENBN0NmLENBQUE7O0FBQUEsa0JBd0RBLEdBQXFCLFNBQUMsQ0FBRCxHQUFBO0FBQ25CLE1BQUEsTUFBQTtBQUFBLEVBQUEsSUFBWSxDQUFBLEtBQUssQ0FBakI7QUFBQSxXQUFPLENBQVAsQ0FBQTtHQUFBO0FBRUEsU0FBTSxDQUFBLE9BQUksQ0FBUSxDQUFSLENBQVYsR0FBQTtBQUNFLElBQUEsTUFBQSxHQUFTLFdBQUEsQ0FBWSxDQUFaLENBQVQsQ0FBQTtBQUFBLElBQ0EsQ0FBQSxJQUFLLE1BREwsQ0FERjtFQUFBLENBRkE7QUFLQSxTQUFPLENBQVAsQ0FObUI7QUFBQSxDQXhEckIsQ0FBQTs7QUFBQSxPQWdFTyxDQUFDLEdBQVIsR0FBYyxTQUFBLEdBQUE7QUFDWixTQUFPLGtCQUFBLENBQW1CLFlBQW5CLENBQVAsQ0FEWTtBQUFBLENBaEVkLENBQUE7Ozs7Ozs7O0FDQUEsSUFBQSxxQkFBQTs7QUFBQSxNQUFNLENBQUMsT0FBUCxHQUFpQixPQUFBLEdBQWMsSUFBQSxPQUFBLENBQVEsaU5BQVIsQ0FBL0IsQ0FBQTs7QUFBQSxZQVdBLEdBQWUsU0FBQyxDQUFELEdBQUE7QUFDYixNQUFBLGdCQUFBO0FBQUEsRUFBQSxHQUFBLEdBQU0sQ0FBQyxDQUFDLFFBQUYsQ0FBQSxDQUFOLENBQUE7QUFDQSxPQUFTLGlHQUFULEdBQUE7QUFDRSxJQUFBLElBQUcsR0FBSSxDQUFBLENBQUEsQ0FBSixLQUFVLEdBQUksQ0FBQSxHQUFHLENBQUMsTUFBSixHQUFhLENBQWIsR0FBaUIsQ0FBakIsQ0FBakI7QUFDRSxhQUFPLEtBQVAsQ0FERjtLQURGO0FBQUEsR0FEQTtBQUlBLFNBQU8sSUFBUCxDQUxhO0FBQUEsQ0FYZixDQUFBOztBQUFBLE9Ba0JPLENBQUMsR0FBUixHQUNFO0FBQUEsRUFBQSxJQUFBLEVBQU0sU0FBQSxHQUFBO0FBRUosUUFBQSw2Q0FBQTtBQUFBO0FBQUEsU0FBQSwyQ0FBQTttQkFBQTtBQUNFLE1BQUEsS0FBQSxDQUFNLFlBQUEsQ0FBYSxDQUFiLENBQU4sRUFBdUIsSUFBdkIsRUFBOEIsZUFBQSxHQUFjLENBQWQsR0FBaUIsZ0JBQS9DLENBQUEsQ0FERjtBQUFBLEtBQUE7QUFFQTtBQUFBO1NBQUEsOENBQUE7b0JBQUE7QUFDRSxvQkFBQSxLQUFBLENBQU0sWUFBQSxDQUFhLENBQWIsQ0FBTixFQUF1QixLQUF2QixFQUErQixlQUFBLEdBQWMsQ0FBZCxHQUFpQixpQkFBaEQsRUFBQSxDQURGO0FBQUE7b0JBSkk7RUFBQSxDQUFOO0FBQUEsRUFPQSxNQUFBLEVBQVEsU0FBQSxHQUFBO0FBQ04sUUFBQSxtREFBQTtBQUFBLElBQUEsUUFBQSxHQUFXLENBQVgsQ0FBQTtBQUFBLElBQ0EsUUFBQSxHQUFXLENBRFgsQ0FBQTtBQUFBLElBRUEsUUFBQSxHQUFXLENBRlgsQ0FBQTtBQUlBLFNBQVMsaUNBQVQsR0FBQTtBQUNFLFdBQVMsaUNBQVQsR0FBQTtBQUNFLFFBQUEsT0FBQSxHQUFVLENBQUEsR0FBSSxDQUFkLENBQUE7QUFDQSxRQUFBLElBQUcsWUFBQSxDQUFhLE9BQWIsQ0FBSDtBQUNFLFVBQUEsUUFBQSxHQUFXLENBQVgsQ0FBQTtBQUFBLFVBQ0EsUUFBQSxHQUFXLENBRFgsQ0FBQTtBQUFBLFVBRUEsUUFBQSxHQUFXLE9BRlgsQ0FERjtTQUZGO0FBQUEsT0FERjtBQUFBLEtBSkE7QUFZQSxXQUFPLFFBQVAsQ0FiTTtFQUFBLENBUFI7Q0FuQkYsQ0FBQTs7Ozs7O0FDQUEsSUFBQSxPQUFBOztBQUFBLE1BQU0sQ0FBQyxPQUFQLEdBQWlCLE9BQUEsR0FBYyxJQUFBLE9BQUEsQ0FBUSxtUkFBUixDQUEvQixDQUFBOztBQUFBLE9BV08sQ0FBQyxHQUFSLEdBQWMsU0FBQSxHQUFBO0FBRVosTUFBQSxlQUFBO0FBQUEsRUFBQSxDQUFBLEdBQUksQ0FBSixDQUFBO0FBQ0EsU0FBQSxJQUFBLEdBQUE7QUFDRSxJQUFBLENBQUEsSUFBSyxFQUFMLENBQUE7QUFBQSxJQUNBLEtBQUEsR0FBUSxJQURSLENBQUE7QUFFQSxTQUFTLDhCQUFULEdBQUE7QUFDRSxNQUFBLElBQUcsQ0FBQyxDQUFBLEdBQUksQ0FBTCxDQUFBLEtBQVcsQ0FBZDtBQUNFLFFBQUEsS0FBQSxHQUFRLEtBQVIsQ0FBQTtBQUNBLGNBRkY7T0FERjtBQUFBLEtBRkE7QUFPQSxJQUFBLElBQVMsS0FBVDtBQUFBLFlBQUE7S0FSRjtFQUFBLENBREE7QUFXQSxTQUFPLENBQVAsQ0FiWTtBQUFBLENBWGQsQ0FBQTs7Ozs7O0FDQUEsSUFBQSx3REFBQTs7QUFBQSxNQUFNLENBQUMsT0FBUCxHQUFpQixPQUFBLEdBQWMsSUFBQSxPQUFBLENBQVEsb2lCQUFSLENBQS9CLENBQUE7O0FBQUEsWUFtQkEsR0FBZSxTQUFDLENBQUQsR0FBQTtBQUNiLE1BQUEsVUFBQTtBQUFBLEVBQUEsR0FBQSxHQUFNLENBQU4sQ0FBQTtBQUNBLE9BQVMsZ0VBQVQsR0FBQTtBQUNFLElBQUEsR0FBQSxJQUFRLENBQUEsR0FBSSxDQUFaLENBREY7QUFBQSxHQURBO0FBR0EsU0FBTyxHQUFQLENBSmE7QUFBQSxDQW5CZixDQUFBOztBQUFBLFdBeUJBLEdBQWMsU0FBQyxDQUFELEdBQUE7QUFDWixNQUFBLFVBQUE7QUFBQSxFQUFBLEdBQUEsR0FBTSxDQUFOLENBQUE7QUFDQSxPQUFTLGdFQUFULEdBQUE7QUFDRSxJQUFBLEdBQUEsSUFBTyxDQUFQLENBREY7QUFBQSxHQURBO0FBR0EsU0FBUSxHQUFBLEdBQU0sR0FBZCxDQUpZO0FBQUEsQ0F6QmQsQ0FBQTs7QUFBQSxvQkErQkEsR0FBdUIsU0FBQyxDQUFELEdBQUE7QUFDckIsU0FBTyxXQUFBLENBQVksQ0FBWixDQUFBLEdBQWlCLFlBQUEsQ0FBYSxDQUFiLENBQXhCLENBRHFCO0FBQUEsQ0EvQnZCLENBQUE7O0FBQUEsT0FrQ08sQ0FBQyxHQUFSLEdBQ0U7QUFBQSxFQUFBLElBQUEsRUFBTSxTQUFBLEdBQUE7QUFDSixJQUFBLEtBQUEsQ0FBTSxZQUFBLENBQWEsRUFBYixDQUFOLEVBQXdCLEdBQXhCLEVBQTZCLG9EQUE3QixDQUFBLENBQUE7QUFBQSxJQUNBLEtBQUEsQ0FBTSxXQUFBLENBQVksRUFBWixDQUFOLEVBQXVCLElBQXZCLEVBQTZCLG9EQUE3QixDQURBLENBQUE7V0FFQSxLQUFBLENBQU0sb0JBQUEsQ0FBcUIsRUFBckIsQ0FBTixFQUFnQyxJQUFoQyxFQUFzQyxnRUFBdEMsRUFISTtFQUFBLENBQU47QUFBQSxFQUtBLE1BQUEsRUFBUSxTQUFBLEdBQUE7QUFDTixXQUFPLG9CQUFBLENBQXFCLEdBQXJCLENBQVAsQ0FETTtFQUFBLENBTFI7Q0FuQ0YsQ0FBQTs7Ozs7O0FDQUEsSUFBQSxpQkFBQTs7QUFBQSxNQUFNLENBQUMsT0FBUCxHQUFpQixPQUFBLEdBQWMsSUFBQSxPQUFBLENBQVEsc01BQVIsQ0FBL0IsQ0FBQTs7QUFBQSxRQVdBLEdBQVcsU0FBQyxDQUFELEdBQUE7QUFDVCxNQUFBLFlBQUE7QUFBQSxFQUFBLEtBQUEsR0FBUSxHQUFBLENBQUEsZ0JBQVIsQ0FBQTtBQUNBLE9BQVMsOERBQVQsR0FBQTtBQUNFLElBQUEsS0FBSyxDQUFDLElBQU4sQ0FBQSxDQUFBLENBREY7QUFBQSxHQURBO0FBR0EsU0FBTyxLQUFLLENBQUMsSUFBTixDQUFBLENBQVAsQ0FKUztBQUFBLENBWFgsQ0FBQTs7QUFBQSxPQWlCTyxDQUFDLEdBQVIsR0FDRTtBQUFBLEVBQUEsSUFBQSxFQUFNLFNBQUEsR0FBQTtXQUNKLEtBQUEsQ0FBTSxRQUFBLENBQVMsQ0FBVCxDQUFOLEVBQW1CLEVBQW5CLEVBQXVCLGlCQUF2QixFQURJO0VBQUEsQ0FBTjtBQUFBLEVBR0EsTUFBQSxFQUFRLFNBQUEsR0FBQTtBQUNOLFdBQU8sUUFBQSxDQUFTLEtBQVQsQ0FBUCxDQURNO0VBQUEsQ0FIUjtDQWxCRixDQUFBOzs7Ozs7QUNBQSxJQUFBLDJDQUFBOztBQUFBLE1BQU0sQ0FBQyxPQUFQLEdBQWlCLE9BQUEsR0FBYyxJQUFBLE9BQUEsQ0FBUSw2M0NBQVIsQ0FBL0IsQ0FBQTs7QUFBQSxHQWdDQSxHQUFNLGdoQ0FoQ04sQ0FBQTs7QUFBQSxHQXNEQSxHQUFNLEdBQUcsQ0FBQyxPQUFKLENBQVksVUFBWixFQUF3QixFQUF4QixDQXRETixDQUFBOztBQUFBLE1BdURBOztBQUFVO09BQUEsMENBQUE7b0JBQUE7QUFBQSxrQkFBQSxRQUFBLENBQVMsS0FBVCxFQUFBLENBQUE7QUFBQTs7SUF2RFYsQ0FBQTs7QUFBQSxjQXlEQSxHQUFpQixTQUFDLFVBQUQsR0FBQTtBQUNmLE1BQUEsNkNBQUE7QUFBQSxFQUFBLElBQVksVUFBQSxHQUFhLE1BQU0sQ0FBQyxNQUFoQztBQUFBLFdBQU8sQ0FBUCxDQUFBO0dBQUE7QUFBQSxFQUVBLE9BQUEsR0FBVSxDQUZWLENBQUE7QUFHQSxPQUFhLHVIQUFiLEdBQUE7QUFDRSxJQUFBLEdBQUEsR0FBTSxLQUFBLEdBQVEsVUFBZCxDQUFBO0FBQUEsSUFDQSxPQUFBLEdBQVUsQ0FEVixDQUFBO0FBRUEsU0FBUyxrRkFBVCxHQUFBO0FBQ0UsTUFBQSxPQUFBLElBQVcsTUFBTyxDQUFBLENBQUEsQ0FBbEIsQ0FERjtBQUFBLEtBRkE7QUFJQSxJQUFBLElBQUcsT0FBQSxHQUFVLE9BQWI7QUFDRSxNQUFBLE9BQUEsR0FBVSxPQUFWLENBREY7S0FMRjtBQUFBLEdBSEE7QUFXQSxTQUFPLE9BQVAsQ0FaZTtBQUFBLENBekRqQixDQUFBOztBQUFBLE9BdUVPLENBQUMsR0FBUixHQUNFO0FBQUEsRUFBQSxJQUFBLEVBQU0sU0FBQSxHQUFBO1dBQ0osS0FBQSxDQUFNLGNBQUEsQ0FBZSxDQUFmLENBQU4sRUFBeUIsSUFBekIsRUFBK0IsK0NBQS9CLEVBREk7RUFBQSxDQUFOO0FBQUEsRUFHQSxNQUFBLEVBQVEsU0FBQSxHQUFBO0FBQ04sV0FBTyxjQUFBLENBQWUsRUFBZixDQUFQLENBRE07RUFBQSxDQUhSO0NBeEVGLENBQUE7Ozs7OztBQ0FBLElBQUEsb0NBQUE7O0FBQUEsTUFBTSxDQUFDLE9BQVAsR0FBaUIsT0FBQSxHQUFjLElBQUEsT0FBQSxDQUFRLGlWQUFSLENBQS9CLENBQUE7O0FBQUEsU0FpQkEsR0FBWSxTQUFDLENBQUQsRUFBSSxDQUFKLEVBQU8sQ0FBUCxHQUFBO0FBQ1YsU0FBTyxDQUFDLENBQUMsQ0FBQSxHQUFFLENBQUgsQ0FBQSxHQUFRLENBQUMsQ0FBQSxHQUFFLENBQUgsQ0FBVCxDQUFBLEtBQW1CLENBQUMsQ0FBQSxHQUFFLENBQUgsQ0FBMUIsQ0FEVTtBQUFBLENBakJaLENBQUE7O0FBQUEsZ0JBb0JBLEdBQW1CLFNBQUMsR0FBRCxHQUFBO0FBQ2pCLE1BQUEsZUFBQTtBQUFBLE9BQVMsK0JBQVQsR0FBQTtBQUNFLFNBQVMsK0JBQVQsR0FBQTtBQUNFLE1BQUEsQ0FBQSxHQUFJLElBQUEsR0FBTyxDQUFQLEdBQVcsQ0FBZixDQUFBO0FBQ0EsTUFBQSxJQUFHLFNBQUEsQ0FBVSxDQUFWLEVBQWEsQ0FBYixFQUFnQixDQUFoQixDQUFIO0FBQ0UsZUFBTyxDQUFDLENBQUQsRUFBSSxDQUFKLEVBQU8sQ0FBUCxDQUFQLENBREY7T0FGRjtBQUFBLEtBREY7QUFBQSxHQUFBO0FBTUEsU0FBTyxLQUFQLENBUGlCO0FBQUEsQ0FwQm5CLENBQUE7O0FBQUEsT0E4Qk8sQ0FBQyxHQUFSLEdBQ0U7QUFBQSxFQUFBLElBQUEsRUFBTSxTQUFBLEdBQUE7V0FDSixLQUFBLENBQU0sU0FBQSxDQUFVLENBQVYsRUFBYSxDQUFiLEVBQWdCLENBQWhCLENBQU4sRUFBMEIsSUFBMUIsRUFBZ0Msa0NBQWhDLEVBREk7RUFBQSxDQUFOO0FBQUEsRUFHQSxNQUFBLEVBQVEsU0FBQSxHQUFBO0FBQ04sV0FBTyxnQkFBQSxDQUFpQixJQUFqQixDQUFQLENBRE07RUFBQSxDQUhSO0NBL0JGLENBQUE7Ozs7QUNBQSxJQUFBLGlCQUFBOztBQUFBLE1BQU0sQ0FBQyxPQUFQLEdBQWlCLE9BQUEsR0FBYyxJQUFBLE9BQUEsQ0FBUSxvTEFBUixDQUEvQixDQUFBOztBQUFBLFFBV0EsR0FBVyxTQUFDLE9BQUQsR0FBQTtBQUNULE1BQUEsYUFBQTtBQUFBLEVBQUEsS0FBQSxHQUFRLEdBQUEsQ0FBQSxnQkFBUixDQUFBO0FBQUEsRUFFQSxHQUFBLEdBQU0sQ0FGTixDQUFBO0FBR0EsU0FBQSxJQUFBLEdBQUE7QUFDRSxJQUFBLENBQUEsR0FBSSxLQUFLLENBQUMsSUFBTixDQUFBLENBQUosQ0FBQTtBQUNBLElBQUEsSUFBRyxDQUFBLElBQUssT0FBUjtBQUNFLFlBREY7S0FEQTtBQUFBLElBR0EsR0FBQSxJQUFPLENBSFAsQ0FERjtFQUFBLENBSEE7QUFTQSxTQUFPLEdBQVAsQ0FWUztBQUFBLENBWFgsQ0FBQTs7QUFBQSxPQXVCTyxDQUFDLEdBQVIsR0FDRTtBQUFBLEVBQUEsSUFBQSxFQUFNLFNBQUEsR0FBQTtXQUNKLEtBQUEsQ0FBTSxRQUFBLENBQVMsRUFBVCxDQUFOLEVBQW9CLEVBQXBCLEVBQXdCLDhCQUF4QixFQURJO0VBQUEsQ0FBTjtBQUFBLEVBR0EsTUFBQSxFQUFRLFNBQUEsR0FBQTtBQUNOLFdBQU8sUUFBQSxDQUFTLE9BQVQsQ0FBUCxDQURNO0VBQUEsQ0FIUjtDQXhCRixDQUFBOzs7Ozs7OztBQ0FBLElBQUEseUZBQUE7O0FBQUEsTUFBTSxDQUFDLE9BQVAsR0FBaUIsT0FBQSxHQUFjLElBQUEsT0FBQSxDQUFRLGl3REFBUixDQUEvQixDQUFBOztBQUFBLFNBa0NBLEdBQVksb3NDQXFCVCxDQUFDLE9BckJRLENBcUJBLFdBckJBLEVBcUJhLEdBckJiLENBbENaLENBQUE7O0FBQUEsTUF5REE7O0FBQVU7QUFBQTtPQUFBLDJDQUFBO3FCQUFBO0FBQUEsa0JBQUEsUUFBQSxDQUFTLEtBQVQsRUFBQSxDQUFBO0FBQUE7O0lBekRWLENBQUE7O0FBQUEsSUEwREEsR0FBTyxLQUFBLENBQU0sRUFBTixDQTFEUCxDQUFBOztBQTJEQSxLQUFTLDZCQUFULEdBQUE7QUFDRSxFQUFBLElBQUssQ0FBQSxDQUFBLENBQUwsR0FBVSxLQUFBLENBQU0sRUFBTixDQUFWLENBREY7QUFBQSxDQTNEQTs7QUFBQSxLQThEQSxHQUFRLENBOURSLENBQUE7O0FBK0RBLEtBQVMsNkJBQVQsR0FBQTtBQUNFLE9BQVMsNkJBQVQsR0FBQTtBQUNFLElBQUEsSUFBSyxDQUFBLENBQUEsQ0FBRyxDQUFBLENBQUEsQ0FBUixHQUFhLE1BQU8sQ0FBQSxLQUFBLENBQXBCLENBQUE7QUFBQSxJQUNBLEtBQUEsRUFEQSxDQURGO0FBQUEsR0FERjtBQUFBLENBL0RBOztBQUFBLGNBc0VBLEdBQWlCLFNBQUMsRUFBRCxFQUFLLEVBQUwsRUFBUyxFQUFULEVBQWEsRUFBYixHQUFBO0FBQ2YsTUFBQSx5QkFBQTtBQUFBLEVBQUEsRUFBQSxHQUFLLEVBQUEsR0FBSyxDQUFDLENBQUEsR0FBSSxFQUFMLENBQVYsQ0FBQTtBQUNBLEVBQUEsSUFBYSxDQUFDLEVBQUEsR0FBSyxDQUFOLENBQUEsSUFBWSxDQUFDLEVBQUEsSUFBTSxFQUFQLENBQXpCO0FBQUEsV0FBTyxDQUFBLENBQVAsQ0FBQTtHQURBO0FBQUEsRUFFQSxFQUFBLEdBQUssRUFBQSxHQUFLLENBQUMsQ0FBQSxHQUFJLEVBQUwsQ0FGVixDQUFBO0FBR0EsRUFBQSxJQUFhLENBQUMsRUFBQSxHQUFLLENBQU4sQ0FBQSxJQUFZLENBQUMsRUFBQSxJQUFNLEVBQVAsQ0FBekI7QUFBQSxXQUFPLENBQUEsQ0FBUCxDQUFBO0dBSEE7QUFBQSxFQUtBLENBQUEsR0FBSSxFQUxKLENBQUE7QUFBQSxFQU1BLENBQUEsR0FBSSxFQU5KLENBQUE7QUFBQSxFQU9BLE9BQUEsR0FBVSxDQVBWLENBQUE7QUFRQSxPQUFTLDRCQUFULEdBQUE7QUFDRSxJQUFBLE9BQUEsSUFBVyxJQUFLLENBQUEsQ0FBQSxDQUFHLENBQUEsQ0FBQSxDQUFuQixDQUFBO0FBQUEsSUFDQSxDQUFBLElBQUssRUFETCxDQUFBO0FBQUEsSUFFQSxDQUFBLElBQUssRUFGTCxDQURGO0FBQUEsR0FSQTtBQWFBLFNBQU8sT0FBUCxDQWRlO0FBQUEsQ0F0RWpCLENBQUE7O0FBQUEsT0FzRkEsR0FBVSxTQUFDLEVBQUQsRUFBSyxFQUFMLEVBQVMsRUFBVCxFQUFhLEVBQWIsR0FBQTtBQUNSLE1BQUEsc0JBQUE7QUFBQSxFQUFBLEVBQUEsR0FBSyxFQUFBLEdBQUssQ0FBQyxDQUFBLEdBQUksRUFBTCxDQUFWLENBQUE7QUFDQSxFQUFBLElBQWEsQ0FBQyxFQUFBLEdBQUssQ0FBTixDQUFBLElBQVksQ0FBQyxFQUFBLElBQU0sRUFBUCxDQUF6QjtBQUFBLFdBQU8sRUFBUCxDQUFBO0dBREE7QUFBQSxFQUVBLEVBQUEsR0FBSyxFQUFBLEdBQUssQ0FBQyxDQUFBLEdBQUksRUFBTCxDQUZWLENBQUE7QUFHQSxFQUFBLElBQWEsQ0FBQyxFQUFBLEdBQUssQ0FBTixDQUFBLElBQVksQ0FBQyxFQUFBLElBQU0sRUFBUCxDQUF6QjtBQUFBLFdBQU8sRUFBUCxDQUFBO0dBSEE7QUFBQSxFQUtBLElBQUEsR0FBTyxFQUxQLENBQUE7QUFBQSxFQU9BLENBQUEsR0FBSSxFQVBKLENBQUE7QUFBQSxFQVFBLENBQUEsR0FBSSxFQVJKLENBQUE7QUFTQSxPQUFTLDRCQUFULEdBQUE7QUFDRSxJQUFBLElBQUksQ0FBQyxJQUFMLENBQVUsSUFBSyxDQUFBLENBQUEsQ0FBRyxDQUFBLENBQUEsQ0FBbEIsQ0FBQSxDQUFBO0FBQUEsSUFDQSxDQUFBLElBQUssRUFETCxDQUFBO0FBQUEsSUFFQSxDQUFBLElBQUssRUFGTCxDQURGO0FBQUEsR0FUQTtBQWNBLFNBQU8sSUFBUCxDQWZRO0FBQUEsQ0F0RlYsQ0FBQTs7QUFBQSxPQXVHTyxDQUFDLEdBQVIsR0FDRTtBQUFBLEVBQUEsSUFBQSxFQUFNLFNBQUEsR0FBQTtBQUVKLElBQUEsRUFBQSxDQUFHLElBQUgsRUFBUyxJQUFJLENBQUMsU0FBTCxDQUFlLE9BQUEsQ0FBUSxDQUFSLEVBQVcsQ0FBWCxFQUFjLENBQWQsRUFBaUIsQ0FBakIsQ0FBZixDQUFULENBQUEsQ0FBQTtBQUFBLElBQ0EsS0FBQSxDQUFNLGNBQUEsQ0FBZSxDQUFmLEVBQWtCLENBQWxCLEVBQXFCLENBQXJCLEVBQXdCLENBQXhCLENBQU4sRUFBa0MsT0FBbEMsRUFBMkMsa0RBQTNDLENBREEsQ0FBQTtBQUFBLElBRUEsS0FBQSxDQUFNLGNBQUEsQ0FBZSxDQUFmLEVBQWtCLENBQWxCLEVBQXFCLENBQXJCLEVBQXdCLENBQXhCLENBQU4sRUFBa0MsUUFBbEMsRUFBNEMsb0RBQTVDLENBRkEsQ0FBQTtXQUdBLEVBQUEsQ0FBRyxJQUFILEVBQVMsSUFBSSxDQUFDLFNBQUwsQ0FBZSxPQUFBLENBQVEsQ0FBUixFQUFXLENBQVgsRUFBYyxDQUFkLEVBQWlCLENBQWpCLENBQWYsQ0FBVCxFQUxJO0VBQUEsQ0FBTjtBQUFBLEVBT0EsTUFBQSxFQUFRLFNBQUEsR0FBQTtBQUlOLFFBQUEsaUJBQUE7QUFBQSxJQUFBLEdBQUEsR0FDRTtBQUFBLE1BQUEsT0FBQSxFQUFTLENBQVQ7QUFBQSxNQUNBLENBQUEsRUFBRyxDQURIO0FBQUEsTUFFQSxDQUFBLEVBQUcsQ0FGSDtBQUFBLE1BR0EsR0FBQSxFQUFLLE9BSEw7S0FERixDQUFBO0FBTUEsU0FBUyw2QkFBVCxHQUFBO0FBQ0UsV0FBUyw2QkFBVCxHQUFBO0FBSUUsUUFBQSxDQUFBLEdBQUksY0FBQSxDQUFlLENBQWYsRUFBa0IsQ0FBbEIsRUFBcUIsQ0FBckIsRUFBd0IsQ0FBeEIsQ0FBSixDQUFBO0FBQ0EsUUFBQSxJQUFHLEdBQUcsQ0FBQyxPQUFKLEdBQWMsQ0FBakI7QUFDRSxVQUFBLEdBQUcsQ0FBQyxPQUFKLEdBQWMsQ0FBZCxDQUFBO0FBQUEsVUFDQSxHQUFHLENBQUMsQ0FBSixHQUFRLENBRFIsQ0FBQTtBQUFBLFVBRUEsR0FBRyxDQUFDLENBQUosR0FBUSxDQUZSLENBQUE7QUFBQSxVQUdBLEdBQUcsQ0FBQyxHQUFKLEdBQVUsT0FIVixDQUFBO0FBSUEsVUFBQSxJQUFHLENBQUEsS0FBSyxRQUFSO0FBQ0UsWUFBQSxPQUFPLENBQUMsR0FBUixDQUFZLEtBQVosQ0FBQSxDQUFBO0FBQUEsWUFDQSxDQUFBLEdBQUksY0FBQSxDQUFlLENBQWYsRUFBa0IsQ0FBbEIsRUFBcUIsQ0FBckIsRUFBd0IsQ0FBeEIsQ0FESixDQUFBO0FBQUEsWUFFQSxPQUFPLENBQUMsR0FBUixDQUFZLENBQVosQ0FGQSxDQURGO1dBTEY7U0FEQTtBQUFBLFFBVUEsQ0FBQSxHQUFJLGNBQUEsQ0FBZSxDQUFmLEVBQWtCLENBQWxCLEVBQXFCLENBQXJCLEVBQXdCLENBQXhCLENBVkosQ0FBQTtBQVdBLFFBQUEsSUFBRyxHQUFHLENBQUMsT0FBSixHQUFjLENBQWpCO0FBQ0UsVUFBQSxHQUFHLENBQUMsT0FBSixHQUFjLENBQWQsQ0FBQTtBQUFBLFVBQ0EsR0FBRyxDQUFDLENBQUosR0FBUSxDQURSLENBQUE7QUFBQSxVQUVBLEdBQUcsQ0FBQyxDQUFKLEdBQVEsQ0FGUixDQUFBO0FBQUEsVUFHQSxHQUFHLENBQUMsR0FBSixHQUFVLE1BSFYsQ0FERjtTQVhBO0FBQUEsUUFnQkEsQ0FBQSxHQUFJLGNBQUEsQ0FBZSxDQUFmLEVBQWtCLENBQWxCLEVBQXFCLENBQXJCLEVBQXdCLENBQXhCLENBaEJKLENBQUE7QUFpQkEsUUFBQSxJQUFHLEdBQUcsQ0FBQyxPQUFKLEdBQWMsQ0FBakI7QUFDRSxVQUFBLEdBQUcsQ0FBQyxPQUFKLEdBQWMsQ0FBZCxDQUFBO0FBQUEsVUFDQSxHQUFHLENBQUMsQ0FBSixHQUFRLENBRFIsQ0FBQTtBQUFBLFVBRUEsR0FBRyxDQUFDLENBQUosR0FBUSxDQUZSLENBQUE7QUFBQSxVQUdBLEdBQUcsQ0FBQyxHQUFKLEdBQVUsVUFIVixDQURGO1NBckJGO0FBQUEsT0FERjtBQUFBLEtBTkE7QUFrQ0EsV0FBTyxHQUFQLENBdENNO0VBQUEsQ0FQUjtDQXhHRixDQUFBOzs7Ozs7QUNBQSxJQUFBLHNCQUFBOztBQUFBLElBQUEsR0FBTyxNQUFQLENBQUE7O0FBQUE7QUFJZSxFQUFBLDBCQUFBLEdBQUE7QUFDWCxJQUFBLElBQUMsQ0FBQSxDQUFELEdBQUssQ0FBTCxDQURXO0VBQUEsQ0FBYjs7QUFBQSw2QkFHQSxJQUFBLEdBQU0sU0FBQSxHQUFBO0FBQ0osUUFBQSxVQUFBO0FBQUEsSUFBQSxJQUFDLENBQUEsQ0FBRCxJQUFNLENBQU4sQ0FBQTtBQUNBLElBQUEsSUFBRyxJQUFDLENBQUEsQ0FBRCxHQUFLLENBQVI7QUFDRSxNQUFBLElBQUcsSUFBQyxDQUFBLENBQUQsR0FBSyxDQUFSO0FBQ0UsUUFBQSxJQUFDLENBQUEsQ0FBRCxHQUFLLENBQUwsQ0FBQTtBQUNBLGVBQU8sQ0FBUCxDQUZGO09BQUE7QUFHQSxNQUFBLElBQUcsSUFBQyxDQUFBLENBQUQsR0FBSyxDQUFSO0FBQ0UsZUFBTyxDQUFQLENBREY7T0FIQTtBQUFBLE1BS0EsSUFBQyxDQUFBLElBQUQsR0FBUSxFQUxSLENBQUE7QUFBQSxNQU1BLElBQUMsQ0FBQSxHQUFELEdBQVcsSUFBQSxnQkFBQSxDQUFBLENBTlgsQ0FBQTtBQUFBLE1BT0EsSUFBQyxDQUFBLEdBQUcsQ0FBQyxJQUFMLENBQUEsQ0FQQSxDQUFBO0FBQUEsTUFRQSxJQUFDLENBQUEsQ0FBRCxHQUFLLElBQUMsQ0FBQSxHQUFHLENBQUMsSUFBTCxDQUFBLENBUkwsQ0FBQTtBQUFBLE1BU0EsSUFBQyxDQUFBLENBQUQsR0FBSyxJQUFDLENBQUEsQ0FBRCxHQUFLLElBQUMsQ0FBQSxDQVRYLENBQUE7QUFVQSxhQUFPLENBQVAsQ0FYRjtLQUFBLE1BQUE7QUFhRSxNQUFBLENBQUEsR0FBSSxJQUFDLENBQUEsSUFBSyxDQUFBLElBQUMsQ0FBQSxDQUFELENBQVYsQ0FBQTtBQUNBLE1BQUEsSUFBRyxDQUFBLENBQUg7QUFDRSxRQUFBLElBQUcsSUFBQyxDQUFBLENBQUQsR0FBSyxJQUFDLENBQUEsQ0FBVDtBQUNFLGlCQUFPLElBQUMsQ0FBQSxDQUFSLENBREY7U0FBQSxNQUFBO0FBR0UsVUFBQSxFQUFBLEdBQUssSUFBQyxDQUFBLENBQUQsSUFBTSxDQUFYLENBQUE7QUFBQSxVQUNBLElBQUMsQ0FBQSxJQUFLLENBQUEsSUFBQyxDQUFBLENBQUQsR0FBSyxFQUFMLENBQU4sR0FBaUIsRUFEakIsQ0FBQTtBQUFBLFVBRUEsSUFBQyxDQUFBLENBQUQsR0FBSyxJQUFDLENBQUEsR0FBRyxDQUFDLElBQUwsQ0FBQSxDQUZMLENBQUE7QUFBQSxVQUdBLElBQUMsQ0FBQSxDQUFELEdBQUssSUFBQyxDQUFBLENBQUQsR0FBSyxJQUFDLENBQUEsQ0FIWCxDQUFBO0FBSUEsaUJBQU8sSUFBQyxDQUFBLElBQUQsQ0FBQSxDQUFQLENBUEY7U0FERjtPQUFBLE1BQUE7QUFVRSxRQUFBLE1BQUEsQ0FBQSxJQUFRLENBQUEsSUFBSyxDQUFBLElBQUMsQ0FBQSxDQUFELENBQWIsQ0FBQTtBQUFBLFFBQ0EsR0FBQSxHQUFNLElBQUMsQ0FBQSxDQUFELEdBQUssQ0FEWCxDQUFBO0FBRUEsZUFBTyxJQUFDLENBQUEsSUFBSyxDQUFBLEdBQUEsQ0FBYixHQUFBO0FBQ0UsVUFBQSxHQUFBLElBQU8sQ0FBUCxDQURGO1FBQUEsQ0FGQTtBQUFBLFFBSUEsSUFBQyxDQUFBLElBQUssQ0FBQSxHQUFBLENBQU4sR0FBYSxDQUpiLENBQUE7QUFLQSxlQUFPLElBQUMsQ0FBQSxJQUFELENBQUEsQ0FBUCxDQWZGO09BZEY7S0FGSTtFQUFBLENBSE4sQ0FBQTs7MEJBQUE7O0lBSkYsQ0FBQTs7QUFBQSxJQXdDSSxDQUFDLGdCQUFMLEdBQXdCLGdCQXhDeEIsQ0FBQTs7OztBQ0FBLElBQUEsMkJBQUE7O0FBQUEsWUFBQSxHQUFlLEVBQWYsQ0FBQTs7QUFBQSxJQUVBLEdBQU8sTUFGUCxDQUFBOztBQUFBLElBSUksQ0FBQyxnQkFBTCxHQUF3QixTQUFDLENBQUQsR0FBQTtBQUN0QixNQUFBLEdBQUE7QUFBQSxFQUFBLEdBQUEsR0FBTSxJQUFJLENBQUMsU0FBTCxDQUFlLENBQWYsQ0FBTixDQUFBO0FBQUEsRUFDQSxHQUFBLEdBQU0sR0FBRyxDQUFDLE9BQUosQ0FBWSxHQUFaLEVBQWlCLEtBQWpCLENBRE4sQ0FBQTtBQUVBLFNBQU8sR0FBUCxDQUhzQjtBQUFBLENBSnhCLENBQUE7O0FBQUEsSUFTSSxDQUFDLE1BQUwsR0FBYyxTQUFBLEdBQUE7QUFDWixNQUFBLHFDQUFBO0FBQUEsRUFBQSxVQUFBLEdBQWEsWUFBYixDQUFBO0FBQUEsRUFDQSxTQUFBLEdBQVksQ0FEWixDQUFBO0FBQUEsRUFHQSxjQUFBLEdBQWlCLFNBQUEsR0FBQTtBQUNmLElBQUEsSUFBRyxTQUFBLEdBQVksVUFBZjtBQUNFLE1BQUEsU0FBQSxFQUFBLENBQUE7YUFDQSxPQUFBLENBQVEsU0FBUixFQUFtQixjQUFuQixFQUZGO0tBRGU7RUFBQSxDQUhqQixDQUFBO1NBT0EsY0FBQSxDQUFBLEVBUlk7QUFBQSxDQVRkLENBQUE7O0FBQUEsSUFtQkksQ0FBQyxlQUFMLEdBQXVCLFNBQUMsSUFBRCxHQUFBO0FBRXJCLE1BQUEsMkJBQUE7QUFBQSxFQUFBLGNBQUEsR0FBaUIsSUFBakIsQ0FBQTtBQUNBLEVBQUEsSUFBRyxJQUFJLENBQUMsUUFBTCxHQUFnQixDQUFuQjtBQUNFLElBQUEsSUFBRyxJQUFJLENBQUMsVUFBTCxJQUFtQixJQUFJLENBQUMsUUFBM0I7QUFDRSxNQUFBLGNBQUEsR0FBaUIsSUFBSSxDQUFDLFVBQXRCLENBQUE7QUFBQSxNQUNBLElBQUksQ0FBQyxVQUFMLEVBREEsQ0FERjtLQURGO0dBQUEsTUFBQTtBQUtFLElBQUEsSUFBRyxJQUFJLENBQUMsSUFBSSxDQUFDLE1BQVYsR0FBbUIsQ0FBdEI7QUFDRSxNQUFBLGNBQUEsR0FBaUIsSUFBSSxDQUFDLElBQUksQ0FBQyxLQUFWLENBQUEsQ0FBakIsQ0FERjtLQUxGO0dBREE7QUFTQSxFQUFBLElBQUcsY0FBQSxLQUFrQixJQUFyQjtBQUNFLElBQUEsV0FBQSxHQUFjLFNBQUEsR0FBQTtBQUNaLE1BQUEsTUFBTSxDQUFDLElBQVAsR0FBYyxJQUFkLENBQUE7YUFDQSxPQUFBLENBQVEsY0FBUixFQUF3QixTQUFBLEdBQUE7ZUFDdEIsZUFBQSxDQUFnQixJQUFoQixFQURzQjtNQUFBLENBQXhCLEVBRlk7SUFBQSxDQUFkLENBQUE7V0FJQSxXQUFBLENBQUEsRUFMRjtHQVhxQjtBQUFBLENBbkJ2QixDQUFBOztBQUFBLElBcUNJLENBQUMsT0FBTCxHQUFlLFNBQUMsS0FBRCxFQUFRLEVBQVIsR0FBQTtBQUNiLE1BQUEsbUJBQUE7QUFBQSxFQUFBLFVBQUEsR0FBYyxHQUFBLEdBQUUsQ0FBQSxDQUFDLEtBQUEsR0FBTSxLQUFQLENBQWEsQ0FBQyxLQUFkLENBQW9CLENBQUEsQ0FBcEIsQ0FBQSxDQUFoQixDQUFBO0FBQUEsRUFDQSxNQUFNLENBQUMsS0FBUCxHQUFlLEtBRGYsQ0FBQTtBQUFBLEVBRUEsT0FBQSxHQUFVLE9BQUEsQ0FBUSxVQUFSLENBRlYsQ0FBQTtBQUFBLEVBR0EsT0FBTyxDQUFDLE9BQVIsQ0FBQSxDQUhBLENBQUE7QUFJQSxFQUFBLElBQTRCLEVBQTVCO1dBQUEsTUFBTSxDQUFDLFVBQVAsQ0FBa0IsRUFBbEIsRUFBc0IsQ0FBdEIsRUFBQTtHQUxhO0FBQUEsQ0FyQ2YsQ0FBQTs7QUFBQTtBQTZDZSxFQUFBLGlCQUFFLFdBQUYsR0FBQTtBQUNYLFFBQUEsS0FBQTtBQUFBLElBRFksSUFBQyxDQUFBLGNBQUEsV0FDYixDQUFBO0FBQUEsSUFBQSxJQUFDLENBQUEsS0FBRCxHQUFTLE1BQU0sQ0FBQyxLQUFoQixDQUFBO0FBQUEsSUFDQSxLQUFBLEdBQVEsSUFBQyxDQUFBLFdBQVcsQ0FBQyxLQUFiLENBQW1CLElBQW5CLENBRFIsQ0FBQTtBQUVjLFdBQU0sS0FBSyxDQUFDLE1BQU4sR0FBZSxDQUFmLElBQXFCLEtBQU0sQ0FBQSxDQUFBLENBQUUsQ0FBQyxNQUFULEtBQW1CLENBQTlDLEdBQUE7QUFBZCxNQUFBLEtBQUssQ0FBQyxLQUFOLENBQUEsQ0FBQSxDQUFjO0lBQUEsQ0FGZDtBQUFBLElBR0EsSUFBQyxDQUFBLEtBQUQsR0FBUyxLQUFLLENBQUMsS0FBTixDQUFBLENBSFQsQ0FBQTtBQUFBLElBSUEsSUFBQyxDQUFBLElBQUQsR0FBUSxLQUFLLENBQUMsS0FBTixDQUFBLENBSlIsQ0FBQTtBQUFBLElBS0EsSUFBQyxDQUFBLFdBQUQsR0FBZSxLQUFLLENBQUMsSUFBTixDQUFXLElBQVgsQ0FMZixDQURXO0VBQUEsQ0FBYjs7QUFBQSxvQkFRQSxHQUFBLEdBQUssU0FBQSxHQUFBO0FBQ0ksSUFBQSxJQUFHLE1BQU0sQ0FBQyxXQUFWO2FBQTJCLE1BQU0sQ0FBQyxXQUFXLENBQUMsR0FBbkIsQ0FBQSxFQUEzQjtLQUFBLE1BQUE7YUFBNkQsSUFBQSxJQUFBLENBQUEsQ0FBTSxDQUFDLE9BQVAsQ0FBQSxFQUE3RDtLQURKO0VBQUEsQ0FSTCxDQUFBOztBQUFBLG9CQVdBLE9BQUEsR0FBUyxTQUFBLEdBQUE7QUFDUCxRQUFBLDREQUFBO0FBQUEsSUFBQSxJQUFHLE1BQU0sQ0FBQyxJQUFJLENBQUMsV0FBZjtBQUNFLE1BQUEsTUFBTSxDQUFDLFFBQVEsQ0FBQyxJQUFoQixDQUFxQixnSEFBckIsQ0FBQSxDQURGO0tBQUE7QUFBQSxJQUdBLGNBQUEsR0FBaUIsQ0FBQyxDQUFDLFFBQVEsQ0FBQyxNQUFYLENBQW1CLGNBQUEsR0FBYSxJQUFDLENBQUEsS0FBZCxHQUFxQixHQUF4QyxDQUhqQixDQUFBO0FBQUEsSUFJQSxNQUFNLENBQUMsUUFBUSxDQUFDLElBQWhCLENBQXNCLGVBQUEsR0FBYyxNQUFNLENBQUMsSUFBSSxDQUFDLEdBQTFCLEdBQStCLEtBQS9CLEdBQW1DLElBQUMsQ0FBQSxLQUFwQyxHQUEyQyxLQUEzQyxHQUErQyxjQUEvQyxHQUErRCxNQUFyRixFQUE0RjtBQUFBLE1BQUUsR0FBQSxFQUFLLElBQVA7S0FBNUYsQ0FKQSxDQUFBO0FBTUEsSUFBQSxJQUFHLE1BQU0sQ0FBQyxJQUFJLENBQUMsV0FBZjtBQUNFLE1BQUEsTUFBTSxDQUFDLFFBQVEsQ0FBQyxJQUFoQixDQUFzQixjQUFBLEdBQWEsSUFBQyxDQUFBLElBQWQsR0FBb0IsR0FBMUMsQ0FBQSxDQUFBO0FBQUEsTUFDQSxNQUFNLENBQUMsUUFBUSxDQUFDLElBQWhCLENBQXNCLGNBQUEsR0FBYSxJQUFDLENBQUEsV0FBZCxHQUEyQixLQUFqRCxDQURBLENBREY7S0FOQTtBQVVBLElBQUEsSUFBRyxJQUFDLENBQUEsR0FBRyxDQUFDLGNBQUwsQ0FBb0IsTUFBcEIsQ0FBSDtBQUNFLE1BQUEsVUFBQSxHQUFhLElBQUMsQ0FBQSxHQUFHLENBQUMsTUFBbEIsQ0FBQTtBQUFBLE1BQ0EsUUFBQSxHQUFXLElBQUMsQ0FBQSxHQUFHLENBQUMsSUFEaEIsQ0FERjtLQUFBLE1BQUE7QUFJRSxNQUFBLFVBQUEsR0FBYSxJQUFDLENBQUEsR0FBZCxDQUFBO0FBQUEsTUFDQSxRQUFBLEdBQVcsTUFEWCxDQUpGO0tBVkE7QUFpQkEsSUFBQSxJQUFHLE1BQU0sQ0FBQyxJQUFJLENBQUMsSUFBZjtBQUNFLE1BQUEsSUFBRyxRQUFBLEtBQVksTUFBZjtBQUNFLFFBQUEsTUFBTSxDQUFDLFFBQVEsQ0FBQyxJQUFoQixDQUFxQiwwQkFBckIsQ0FBQSxDQURGO09BQUEsTUFBQTtBQUdFLFFBQUEsUUFBQSxDQUFBLENBQUEsQ0FIRjtPQURGO0tBakJBO0FBdUJBLElBQUEsSUFBRyxNQUFNLENBQUMsSUFBSSxDQUFDLE1BQWY7QUFDRSxNQUFBLEtBQUEsR0FBUSxJQUFDLENBQUEsR0FBRCxDQUFBLENBQVIsQ0FBQTtBQUFBLE1BQ0EsTUFBQSxHQUFTLFVBQUEsQ0FBQSxDQURULENBQUE7QUFBQSxNQUVBLEdBQUEsR0FBTSxJQUFDLENBQUEsR0FBRCxDQUFBLENBRk4sQ0FBQTtBQUFBLE1BR0EsRUFBQSxHQUFLLEdBQUEsR0FBTSxLQUhYLENBQUE7YUFJQSxNQUFNLENBQUMsUUFBUSxDQUFDLElBQWhCLENBQXNCLHFEQUFBLEdBQW9ELENBQUEsRUFBRSxDQUFDLE9BQUgsQ0FBVyxDQUFYLENBQUEsQ0FBcEQsR0FBbUUsb0JBQW5FLEdBQXNGLENBQUEsZ0JBQUEsQ0FBaUIsTUFBakIsQ0FBQSxDQUF0RixHQUFnSCxHQUF0SSxFQUxGO0tBeEJPO0VBQUEsQ0FYVCxDQUFBOztpQkFBQTs7SUE3Q0YsQ0FBQTs7QUFBQSxJQXVGSSxDQUFDLE9BQUwsR0FBZSxPQXZGZixDQUFBOztBQUFBLElBeUZJLENBQUMsRUFBTCxHQUFVLFNBQUMsQ0FBRCxFQUFJLEdBQUosR0FBQTtTQUNSLE1BQU0sQ0FBQyxRQUFRLENBQUMsSUFBaEIsQ0FBc0IsbUJBQUEsR0FBa0IsQ0FBbEIsR0FBcUIsSUFBckIsR0FBd0IsR0FBOUMsRUFEUTtBQUFBLENBekZWLENBQUE7O0FBQUEsSUE0RkksQ0FBQyxLQUFMLEdBQWEsU0FBQyxDQUFELEVBQUksQ0FBSixFQUFPLEdBQVAsR0FBQTtBQUNYLEVBQUEsSUFBRyxDQUFBLEtBQUssQ0FBUjtXQUNFLE1BQU0sQ0FBQyxRQUFRLENBQUMsSUFBaEIsQ0FBc0IscUNBQUEsR0FBb0MsR0FBcEMsR0FBeUMsR0FBL0QsRUFERjtHQUFBLE1BQUE7V0FHRSxNQUFNLENBQUMsUUFBUSxDQUFDLElBQWhCLENBQXNCLHFDQUFBLEdBQW9DLEdBQXBDLEdBQXlDLElBQXpDLEdBQTRDLENBQTVDLEdBQStDLE1BQS9DLEdBQW9ELENBQXBELEdBQXVELElBQTdFLEVBSEY7R0FEVztBQUFBLENBNUZiLENBQUE7O0FBQUEsSUFrR0ksQ0FBQyxTQUFMLEdBQWlCLENBQUEsU0FBQSxLQUFBLEdBQUE7U0FBQSxTQUFDLE9BQUQsR0FBQTtBQUNmLFFBQUEsbURBQUE7QUFBQSxJQUFBLElBQVUsT0FBTyxDQUFDLE1BQVIsS0FBa0IsQ0FBNUI7QUFBQSxZQUFBLENBQUE7S0FBQTtBQUFBLElBQ0EsR0FBQSxHQUFNLENBQUMsQ0FBQyxRQUFRLENBQUMsWUFBWCxDQUF3QixPQUF4QixDQUROLENBQUE7QUFFQSxJQUFBLElBQVUsR0FBRyxDQUFDLElBQUksQ0FBQyxNQUFULEtBQW1CLENBQTdCO0FBQUEsWUFBQSxDQUFBO0tBRkE7QUFBQSxJQUlBLE9BQU8sQ0FBQyxHQUFSLENBQVksR0FBWixDQUpBLENBQUE7QUFBQSxJQU1BLE9BQUEsR0FBVSxLQU5WLENBQUE7QUFBQSxJQVFBLElBQUEsR0FDRTtBQUFBLE1BQUEsVUFBQSxFQUFZLENBQVo7QUFBQSxNQUNBLFFBQUEsRUFBVSxDQURWO0FBQUEsTUFFQSxJQUFBLEVBQU0sRUFGTjtBQUFBLE1BR0EsV0FBQSxFQUFhLEtBSGI7QUFBQSxNQUlBLElBQUEsRUFBTSxLQUpOO0FBQUEsTUFLQSxNQUFBLEVBQVEsS0FMUjtLQVRGLENBQUE7QUFBQSxJQWdCQSxPQUFBLEdBQVUsSUFoQlYsQ0FBQTtBQWtCQTtBQUFBLFNBQUEsMkNBQUE7cUJBQUE7QUFDRSxNQUFBLEdBQUEsR0FBTSxNQUFBLENBQU8sR0FBUCxDQUFOLENBQUE7QUFDQSxNQUFBLElBQVksR0FBRyxDQUFDLE1BQUosR0FBYSxDQUF6QjtBQUFBLGlCQUFBO09BREE7QUFFQSxNQUFBLElBQUcsR0FBSSxDQUFBLENBQUEsQ0FBSixLQUFVLEdBQWI7QUFDRSxRQUFBLE9BQUEsR0FBVSxJQUFWLENBREY7T0FBQSxNQUVLLElBQUcsR0FBRyxDQUFDLEtBQUosQ0FBVSxPQUFWLENBQUg7QUFDSCxRQUFBLENBQUEsR0FBSSxRQUFBLENBQVMsR0FBVCxDQUFKLENBQUE7QUFDQSxRQUFBLElBQUcsQ0FBQyxDQUFBLElBQUssQ0FBTixDQUFBLElBQWEsQ0FBQyxDQUFBLElBQUssWUFBTixDQUFoQjtBQUNFLFVBQUEsSUFBSSxDQUFDLElBQUksQ0FBQyxJQUFWLENBQWUsQ0FBZixDQUFBLENBREY7U0FBQSxNQUFBO0FBR0UsVUFBQSxPQUFBLEdBQVUsS0FBVixDQUFBO0FBQUEsVUFDQSxNQUFNLENBQUMsUUFBUSxDQUFDLElBQWhCLENBQXNCLDRCQUFBLEdBQTJCLENBQTNCLEdBQThCLGtCQUE5QixHQUErQyxZQUEvQyxHQUE2RCxJQUFuRixDQURBLENBSEY7U0FGRztPQUxQO0FBQUEsS0FsQkE7QUErQkEsSUFBQSxJQUFHLElBQUksQ0FBQyxJQUFJLENBQUMsTUFBVixLQUFvQixDQUF2QjtBQUNFLE1BQUEsSUFBSSxDQUFDLFVBQUwsR0FBa0IsQ0FBbEIsQ0FBQTtBQUFBLE1BQ0EsSUFBSSxDQUFDLFFBQUwsR0FBZ0IsWUFEaEIsQ0FERjtLQS9CQTtBQW9DQSxJQUFBLElBQUcsR0FBRyxDQUFDLElBQUssQ0FBQSxDQUFBLENBQVQsS0FBZSxHQUFsQjtBQUNFLE1BQUEsSUFBSSxDQUFDLEdBQUwsR0FBVyxNQUFYLENBREY7S0FBQSxNQUVLLElBQUcsR0FBRyxDQUFDLElBQUssQ0FBQSxDQUFBLENBQVQsS0FBZSxHQUFsQjtBQUNILE1BQUEsSUFBSSxDQUFDLEdBQUwsR0FBVyxVQUFYLENBQUE7QUFBQSxNQUNBLElBQUksQ0FBQyxXQUFMLEdBQW1CLElBRG5CLENBREc7S0FBQSxNQUdBLElBQUcsR0FBRyxDQUFDLElBQUssQ0FBQSxDQUFBLENBQVQsS0FBZSxHQUFsQjtBQUNILE1BQUEsSUFBSSxDQUFDLEdBQUwsR0FBVyxNQUFYLENBQUE7QUFBQSxNQUNBLElBQUksQ0FBQyxJQUFMLEdBQVksSUFEWixDQURHO0tBQUEsTUFHQSxJQUFHLEdBQUcsQ0FBQyxJQUFLLENBQUEsQ0FBQSxDQUFULEtBQWUsR0FBbEI7QUFDSCxNQUFBLElBQUksQ0FBQyxHQUFMLEdBQVcsUUFBWCxDQUFBO0FBQUEsTUFDQSxJQUFJLENBQUMsTUFBTCxHQUFjLElBRGQsQ0FERztLQUFBLE1BR0EsSUFBRyxHQUFHLENBQUMsSUFBSyxDQUFBLENBQUEsQ0FBVCxLQUFlLEdBQWxCO0FBQ0gsTUFBQSxJQUFJLENBQUMsR0FBTCxHQUFXLEtBQVgsQ0FBQTtBQUFBLE1BQ0EsSUFBSSxDQUFDLElBQUwsR0FBWSxJQURaLENBQUE7QUFBQSxNQUVBLElBQUksQ0FBQyxNQUFMLEdBQWMsSUFGZCxDQURHO0tBQUEsTUFJQSxJQUFHLEdBQUcsQ0FBQyxJQUFLLENBQUEsQ0FBQSxDQUFULEtBQWUsR0FBbEI7QUFDSCxNQUFBLElBQUksQ0FBQyxHQUFMLEdBQVcsVUFBWCxDQUFBO0FBQUEsTUFDQSxJQUFJLENBQUMsV0FBTCxHQUFtQixJQURuQixDQURHO0tBQUEsTUFHQSxJQUFHLEdBQUcsQ0FBQyxJQUFLLENBQUEsQ0FBQSxDQUFULEtBQWUsR0FBbEI7QUFDSCxNQUFBLElBQUksQ0FBQyxHQUFMLEdBQVcsTUFBWCxDQUFBO0FBQUEsTUFDQSxPQUFBLEdBQVUsS0FEVixDQUFBO0FBQUEsTUFFQSxNQUFNLENBQUMsUUFBUSxDQUFDLElBQWhCLENBQXdCLHFXQUFBLEdBVWtDLFlBVmxDLEdBVWdELGlLQVZ4RSxDQUZBLENBREc7S0FBQSxNQUFBO0FBa0JILE1BQUEsT0FBQSxHQUFVLEtBQVYsQ0FBQTtBQUFBLE1BQ0EsTUFBTSxDQUFDLFFBQVEsQ0FBQyxJQUFoQixDQUFxQiwrQkFBckIsQ0FEQSxDQWxCRztLQXRETDtBQTJFQSxJQUFBLElBQUcsT0FBSDtBQUNFLE1BQUEsSUFBSSxDQUFDLFdBQUwsR0FBbUIsSUFBbkIsQ0FERjtLQTNFQTtBQThFQSxJQUFBLElBQUcsT0FBSDthQUNFLGVBQUEsQ0FBZ0IsSUFBaEIsRUFERjtLQS9FZTtFQUFBLEVBQUE7QUFBQSxDQUFBLENBQUEsQ0FBQSxJQUFBLENBbEdqQixDQUFBIiwic291cmNlc0NvbnRlbnQiOlsiKGZ1bmN0aW9uIGUodCxuLHIpe2Z1bmN0aW9uIHMobyx1KXtpZighbltvXSl7aWYoIXRbb10pe3ZhciBhPXR5cGVvZiByZXF1aXJlPT1cImZ1bmN0aW9uXCImJnJlcXVpcmU7aWYoIXUmJmEpcmV0dXJuIGEobywhMCk7aWYoaSlyZXR1cm4gaShvLCEwKTt0aHJvdyBuZXcgRXJyb3IoXCJDYW5ub3QgZmluZCBtb2R1bGUgJ1wiK28rXCInXCIpfXZhciBmPW5bb109e2V4cG9ydHM6e319O3Rbb11bMF0uY2FsbChmLmV4cG9ydHMsZnVuY3Rpb24oZSl7dmFyIG49dFtvXVsxXVtlXTtyZXR1cm4gcyhuP246ZSl9LGYsZi5leHBvcnRzLGUsdCxuLHIpfXJldHVybiBuW29dLmV4cG9ydHN9dmFyIGk9dHlwZW9mIHJlcXVpcmU9PVwiZnVuY3Rpb25cIiYmcmVxdWlyZTtmb3IodmFyIG89MDtvPHIubGVuZ3RoO28rKylzKHJbb10pO3JldHVybiBzfSkiLCJtb2R1bGUuZXhwb3J0cyA9IHByb2JsZW0gPSBuZXcgUHJvYmxlbSBcIlwiXCJcblxuUHJvYmxlbSAxOiBNdWx0aXBsZXMgb2YgMyBhbmQgNVxuLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLVxuXG5JZiB3ZSBsaXN0IGFsbCB0aGUgbmF0dXJhbCBudW1iZXJzIGJlbG93IDEwIHRoYXQgYXJlIG11bHRpcGxlcyBvZiAzIG9yIDUsIHdlIGdldCAzLCA1LCA2IGFuZCA5LlxuVGhlIHN1bSBvZiB0aGVzZSBtdWx0aXBsZXMgaXMgMjMuXG5cbkZpbmQgdGhlIHN1bSBvZiBhbGwgdGhlIG11bHRpcGxlcyBvZiAzIG9yIDUgYmVsb3cgMTAwMC5cblxuXCJcIlwiXG5cbnByb2JsZW0ucnVuID1cbiAgdGVzdDogLT5cbiAgICBzdW0gPSAwXG4gICAgZm9yIGkgaW4gWzEuLi4xMF1cbiAgICAgIGlmIChpICUgMyA9PSAwKSBvciAoaSAlIDUgPT0gMClcbiAgICAgICAgc3VtICs9IGlcbiAgICBlcXVhbChzdW0sIDIzLCBcIlN1bSBvZiBuYXR1cmFsIG51bWJlcnMgPCAxMDogI3tzdW19XCIpXG5cbiAgYW5zd2VyOiAtPlxuICAgIHN1bSA9IDBcbiAgICBmb3IgaSBpbiBbMS4uLjEwMDBdXG4gICAgICBpZiAoaSAlIDMgPT0gMCkgb3IgKGkgJSA1ID09IDApXG4gICAgICAgIHN1bSArPSBpXG5cbiAgICByZXR1cm4gc3VtXG4iLCJtb2R1bGUuZXhwb3J0cyA9IHByb2JsZW0gPSBuZXcgUHJvYmxlbSBcIlwiXCJcblxuUHJvYmxlbSAyOiBFdmVuIEZpYm9uYWNjaSBudW1iZXJzXG4tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS1cblxuRWFjaCBuZXcgdGVybSBpbiB0aGUgRmlib25hY2NpIHNlcXVlbmNlIGlzIGdlbmVyYXRlZCBieSBhZGRpbmcgdGhlIHByZXZpb3VzIHR3byB0ZXJtcy5cbkJ5IHN0YXJ0aW5nIHdpdGggMSBhbmQgMiwgdGhlIGZpcnN0IDEwIHRlcm1zIHdpbGwgYmU6XG5cbjEsIDIsIDMsIDUsIDgsIDEzLCAyMSwgMzQsIDU1LCA4OSwgLi4uXG5cbkJ5IGNvbnNpZGVyaW5nIHRoZSB0ZXJtcyBpbiB0aGUgRmlib25hY2NpIHNlcXVlbmNlIHdob3NlIHZhbHVlcyBkbyBub3QgZXhjZWVkIGZvdXIgbWlsbGlvbixcbmZpbmQgdGhlIHN1bSBvZiB0aGUgZXZlbi12YWx1ZWQgdGVybXMuXG5cblwiXCJcIlxuXG5wcm9ibGVtLnJ1biA9IC0+XG5cbiAgcHJldiA9IDFcbiAgY3VyciA9IDFcbiAgc3VtID0gMFxuXG4gIHdoaWxlIGN1cnIgPCA0MDAwMDAwXG4gICAgaWYgKGN1cnIgJSAyKSA9PSAwXG4gICAgICBzdW0gKz0gY3VyclxuXG4gICAgbmV4dCA9IGN1cnIgKyBwcmV2XG4gICAgcHJldiA9IGN1cnJcbiAgICBjdXJyID0gbmV4dFxuXG4gIHJldHVybiBzdW1cbiIsIm1vZHVsZS5leHBvcnRzID0gcHJvYmxlbSA9IG5ldyBQcm9ibGVtIFwiXCJcIlxuXG5Qcm9ibGVtIDM6IExhcmdlc3QgcHJpbWUgZmFjdG9yXG4tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tXG5cblRoZSBwcmltZSBmYWN0b3JzIG9mIDEzMTk1IGFyZSA1LCA3LCAxMyBhbmQgMjkuXG5cbldoYXQgaXMgdGhlIGxhcmdlc3QgcHJpbWUgZmFjdG9yIG9mIHRoZSBudW1iZXIgNjAwODUxNDc1MTQzID9cblxuXCJcIlwiXG5cbiMgLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS1cbiMgU2hhbWVsZXNzbHkgcGlsZmVyZWQvYWRvcHRlZCBmcm9tIGh0dHA6Ly93d3cuamF2YXNjcmlwdGVyLm5ldC9mYXEvbnVtYmVyaXNwcmltZS5odG1cblxubGVhc3RGYWN0b3IgPSAobikgLT5cbiAgcmV0dXJuIE5hTiBpZiBpc05hTihuKSBvciBub3QgaXNGaW5pdGUobilcbiAgcmV0dXJuIDAgaWYgbiA9PSAwXG4gIHJldHVybiAxIGlmIChuICUgMSkgIT0gMCBvciAobiAqIG4pIDwgMlxuICByZXR1cm4gMiBpZiAobiAlIDIpID09IDBcbiAgcmV0dXJuIDMgaWYgKG4gJSAzKSA9PSAwXG4gIHJldHVybiA1IGlmIChuICUgNSkgPT0gMFxuXG4gIG0gPSBNYXRoLnNxcnQgblxuICBmb3IgaSBpbiBbNy4ubV0gYnkgMzBcbiAgICByZXR1cm4gaSAgICBpZiAobiAlIGkpICAgICAgPT0gMFxuICAgIHJldHVybiBpKzQgIGlmIChuICUgKGkrNCkpICA9PSAwXG4gICAgcmV0dXJuIGkrNiAgaWYgKG4gJSAoaSs2KSkgID09IDBcbiAgICByZXR1cm4gaSsxMCBpZiAobiAlIChpKzEwKSkgPT0gMFxuICAgIHJldHVybiBpKzEyIGlmIChuICUgKGkrMTIpKSA9PSAwXG4gICAgcmV0dXJuIGkrMTYgaWYgKG4gJSAoaSsxNikpID09IDBcbiAgICByZXR1cm4gaSsyMiBpZiAobiAlIChpKzIyKSkgPT0gMFxuICAgIHJldHVybiBpKzI0IGlmIChuICUgKGkrMjQpKSA9PSAwXG5cbiAgcmV0dXJuIG5cblxuaXNQcmltZSA9IChuKSAtPlxuICBpZiBpc05hTihuKSBvciBub3QgaXNGaW5pdGUobikgb3IgKG4gJSAxKSAhPSAwIG9yIChuIDwgMilcbiAgICByZXR1cm4gZmFsc2VcbiAgaWYgbiA9PSBsZWFzdEZhY3RvcihuKVxuICAgIHJldHVybiB0cnVlXG5cbiAgcmV0dXJuIGZhbHNlXG5cbiMgLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS1cblxucHJpbWVGYWN0b3JzID0gKG4pIC0+XG4gIHJldHVybiBbMV0gaWYgbiA9PSAxXG5cbiAgZmFjdG9ycyA9IFtdXG4gIHdoaWxlIG5vdCBpc1ByaW1lKG4pXG4gICAgZmFjdG9yID0gbGVhc3RGYWN0b3IobilcbiAgICBmYWN0b3JzLnB1c2ggZmFjdG9yXG4gICAgbiAvPSBmYWN0b3JcbiAgZmFjdG9ycy5wdXNoIG5cbiAgcmV0dXJuIGZhY3RvcnNcblxubGFyZ2VzdFByaW1lRmFjdG9yID0gKG4pIC0+XG4gIHJldHVybiAxIGlmIG4gPT0gMVxuXG4gIHdoaWxlIG5vdCBpc1ByaW1lKG4pXG4gICAgZmFjdG9yID0gbGVhc3RGYWN0b3IobilcbiAgICBuIC89IGZhY3RvclxuICByZXR1cm4gblxuXG5wcm9ibGVtLnJ1biA9IC0+XG4gIHJldHVybiBsYXJnZXN0UHJpbWVGYWN0b3IoNjAwODUxNDc1MTQzKVxuIiwibW9kdWxlLmV4cG9ydHMgPSBwcm9ibGVtID0gbmV3IFByb2JsZW0gXCJcIlwiXG5cblByb2JsZW0gNDogTGFyZ2VzdCBwYWxpbmRyb21lIHByb2R1Y3Rcbi0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS1cblxuQSBwYWxpbmRyb21pYyBudW1iZXIgcmVhZHMgdGhlIHNhbWUgYm90aCB3YXlzLlxuXG5GaW5kIHRoZSBsYXJnZXN0IHBhbGluZHJvbWUgbWFkZSBmcm9tIHRoZSBwcm9kdWN0IG9mIHR3byAzLWRpZ2l0IG51bWJlcnMuXG5cblwiXCJcIlxuXG5pc1BhbGluZHJvbWUgPSAobikgLT5cbiAgc3RyID0gbi50b1N0cmluZygpXG4gIGZvciBpIGluIFswLi4uKHN0ci5sZW5ndGggLyAyKV1cbiAgICBpZiBzdHJbaV0gIT0gc3RyW3N0ci5sZW5ndGggLSAxIC0gaV1cbiAgICAgIHJldHVybiBmYWxzZVxuICByZXR1cm4gdHJ1ZVxuXG5wcm9ibGVtLnJ1biA9XG4gIHRlc3Q6IC0+XG4gICAgIyBNYWtlIHN1cmUgaXNQYWxpbmRyb21lIHdvcmtzIHByb3Blcmx5IGZpcnN0XG4gICAgZm9yIHYgaW4gWzEsIDExLCAxMjEsIDEyMjEsIDEyMzIxLCAxMjM0MzIxXVxuICAgICAgZXF1YWwoaXNQYWxpbmRyb21lKHYpLCB0cnVlLCBcImlzUGFsaW5kcm9tZSgje3Z9KSByZXR1cm5zIHRydWVcIilcbiAgICBmb3IgdiBpbiBbMTIsIDEyMywgMTIzNCwgMTIzNDUsIDEyMzQ1NiwgMTIzMjRdXG4gICAgICBlcXVhbChpc1BhbGluZHJvbWUodiksIGZhbHNlLCBcImlzUGFsaW5kcm9tZSgje3Z9KSByZXR1cm5zIGZhbHNlXCIpXG5cbiAgYW5zd2VyOiAtPlxuICAgIGxhcmdlc3RpID0gMFxuICAgIGxhcmdlc3RqID0gMFxuICAgIGxhcmdlc3RwID0gMFxuXG4gICAgZm9yIGkgaW4gWzEwMC4uOTk5XVxuICAgICAgZm9yIGogaW4gWzEwMC4uOTk5XVxuICAgICAgICBwcm9kdWN0ID0gaSAqIGpcbiAgICAgICAgaWYgaXNQYWxpbmRyb21lKHByb2R1Y3QpXG4gICAgICAgICAgbGFyZ2VzdGkgPSBpXG4gICAgICAgICAgbGFyZ2VzdGogPSBqXG4gICAgICAgICAgbGFyZ2VzdHAgPSBwcm9kdWN0XG5cbiAgICByZXR1cm4gbGFyZ2VzdHBcbiIsIm1vZHVsZS5leHBvcnRzID0gcHJvYmxlbSA9IG5ldyBQcm9ibGVtIFwiXCJcIlxuXG5Qcm9ibGVtIDU6IFNtYWxsZXN0IG11bHRpcGxlXG4tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tXG5cbjI1MjAgaXMgdGhlIHNtYWxsZXN0IG51bWJlciB0aGF0IGNhbiBiZSBkaXZpZGVkIGJ5IGVhY2ggb2YgdGhlIG51bWJlcnMgZnJvbSAxIHRvIDEwIHdpdGhvdXQgYW55IHJlbWFpbmRlci5cblxuV2hhdCBpcyB0aGUgc21hbGxlc3QgcG9zaXRpdmUgbnVtYmVyIHRoYXQgaXMgZXZlbmx5IGRpdmlzaWJsZSBieSBhbGwgb2YgdGhlIG51bWJlcnMgZnJvbSAxIHRvIDIwP1xuXG5cIlwiXCJcblxucHJvYmxlbS5ydW4gPSAtPlxuXG4gIG4gPSAwXG4gIGxvb3BcbiAgICBuICs9IDIwICMgUHJvYmFibHkgY291bGQgYmUgc29tZSBjbGV2ZXIgc3VtIG9mIHByaW1lcyBiZXR3ZWVuIDEtMjAgb3Igc29tZXRoaW5nLiBJIGRvbid0IGNhcmUuXG4gICAgZm91bmQgPSB0cnVlXG4gICAgZm9yIGkgaW4gWzEuLjIwXVxuICAgICAgaWYgKG4gJSBpKSAhPSAwXG4gICAgICAgIGZvdW5kID0gZmFsc2VcbiAgICAgICAgYnJlYWtcblxuICAgIGJyZWFrIGlmIGZvdW5kXG5cbiAgcmV0dXJuIG5cbiIsIm1vZHVsZS5leHBvcnRzID0gcHJvYmxlbSA9IG5ldyBQcm9ibGVtIFwiXCJcIlxuXG5Qcm9ibGVtIDY6IFN1bSBzcXVhcmUgZGlmZmVyZW5jZVxuLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS1cblxuVGhlIHN1bSBvZiB0aGUgc3F1YXJlcyBvZiB0aGUgZmlyc3QgdGVuIG5hdHVyYWwgbnVtYmVycyBpcyxcblxuICAgICAgICAgICAgIDFeMiArIDJeMiArIC4uLiArIDEwXjIgPSAzODVcblxuVGhlIHNxdWFyZSBvZiB0aGUgc3VtIG9mIHRoZSBmaXJzdCB0ZW4gbmF0dXJhbCBudW1iZXJzIGlzLFxuXG4gICAgICAgICAgKDEgKyAyICsgLi4uICsgMTApXjIgPSA1NV4yID0gMzAyNVxuXG5IZW5jZSB0aGUgZGlmZmVyZW5jZSBiZXR3ZWVuIHRoZSBzdW0gb2YgdGhlIHNxdWFyZXMgb2YgdGhlIGZpcnN0IHRlbiBuYXR1cmFsIG51bWJlcnMgYW5kIHRoZSBzcXVhcmUgb2YgdGhlIHN1bSBpcyAzMDI1IOKIkiAzODUgPSAyNjQwLlxuXG5GaW5kIHRoZSBkaWZmZXJlbmNlIGJldHdlZW4gdGhlIHN1bSBvZiB0aGUgc3F1YXJlcyBvZiB0aGUgZmlyc3Qgb25lIGh1bmRyZWQgbmF0dXJhbCBudW1iZXJzIGFuZCB0aGUgc3F1YXJlIG9mIHRoZSBzdW0uXG5cblwiXCJcIlxuXG5zdW1PZlNxdWFyZXMgPSAobikgLT5cbiAgc3VtID0gMFxuICBmb3IgaSBpbiBbMS4ubl1cbiAgICBzdW0gKz0gKGkgKiBpKVxuICByZXR1cm4gc3VtXG5cbnNxdWFyZU9mU3VtID0gKG4pIC0+XG4gIHN1bSA9IDBcbiAgZm9yIGkgaW4gWzEuLm5dXG4gICAgc3VtICs9IGlcbiAgcmV0dXJuIChzdW0gKiBzdW0pXG5cbmRpZmZlcmVuY2VTdW1TcXVhcmVzID0gKG4pIC0+XG4gIHJldHVybiBzcXVhcmVPZlN1bShuKSAtIHN1bU9mU3F1YXJlcyhuKVxuXG5wcm9ibGVtLnJ1biA9XG4gIHRlc3Q6IC0+XG4gICAgZXF1YWwoc3VtT2ZTcXVhcmVzKDEwKSwgMzg1LCBcIlN1bSBvZiBzcXVhcmVzIG9mIGZpcnN0IHRlbiBuYXR1cmFsIG51bWJlcnMgaXMgMzg1XCIpXG4gICAgZXF1YWwoc3F1YXJlT2ZTdW0oMTApLCAzMDI1LCBcIlNxdWFyZSBvZiBzdW0gb2YgZmlyc3QgdGVuIG5hdHVyYWwgbnVtYmVycyBpcyAzMDI1XCIpXG4gICAgZXF1YWwoZGlmZmVyZW5jZVN1bVNxdWFyZXMoMTApLCAyNjQwLCBcIkRpZmZlcmVuY2UgaW4gdmFsdWVzIGZvciB0aGUgZmlyc3QgdGVuIG5hdHVyYWwgbnVtYmVycyBpcyAyNjQwXCIpXG5cbiAgYW5zd2VyOiAtPlxuICAgIHJldHVybiBkaWZmZXJlbmNlU3VtU3F1YXJlcygxMDApXG4iLCJtb2R1bGUuZXhwb3J0cyA9IHByb2JsZW0gPSBuZXcgUHJvYmxlbSBcIlwiXCJcblxuUHJvYmxlbSA3OiAxMDAwMXN0IHByaW1lXG4tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS1cblxuQnkgbGlzdGluZyB0aGUgZmlyc3Qgc2l4IHByaW1lIG51bWJlcnM6IDIsIDMsIDUsIDcsIDExLCBhbmQgMTMsIHdlIGNhbiBzZWUgdGhhdCB0aGUgNnRoIHByaW1lIGlzIDEzLlxuXG5XaGF0IGlzIHRoZSAxMCwwMDFzdCBwcmltZSBudW1iZXI/XG5cblwiXCJcIlxuXG5udGhQcmltZSA9IChuKSAtPlxuICBzaWV2ZSA9IG5ldyBJbmNyZW1lbnRhbFNpZXZlXG4gIGZvciBpIGluIFsxLi4ubl1cbiAgICBzaWV2ZS5uZXh0KClcbiAgcmV0dXJuIHNpZXZlLm5leHQoKVxuXG5wcm9ibGVtLnJ1biA9XG4gIHRlc3Q6IC0+XG4gICAgZXF1YWwobnRoUHJpbWUoNiksIDEzLCBcIjZ0aCBwcmltZSBpcyAxM1wiKVxuXG4gIGFuc3dlcjogLT5cbiAgICByZXR1cm4gbnRoUHJpbWUoMTAwMDEpXG4iLCJtb2R1bGUuZXhwb3J0cyA9IHByb2JsZW0gPSBuZXcgUHJvYmxlbSBcIlwiXCJcblxuUHJvYmxlbSA4OiBMYXJnZXN0IHByb2R1Y3QgaW4gYSBzZXJpZXNcbi0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tXG5cblRoZSBmb3VyIGFkamFjZW50IGRpZ2l0cyBpbiB0aGUgMTAwMC1kaWdpdCBudW1iZXIgdGhhdCBoYXZlIHRoZSBncmVhdGVzdCBwcm9kdWN0IGFyZSA5IHggOSB4IDggeCA5ID0gNTgzMi5cblxuICA3MzE2NzE3NjUzMTMzMDYyNDkxOTIyNTExOTY3NDQyNjU3NDc0MjM1NTM0OTE5NDkzNFxuICA5Njk4MzUyMDMxMjc3NDUwNjMyNjIzOTU3ODMxODAxNjk4NDgwMTg2OTQ3ODg1MTg0M1xuICA4NTg2MTU2MDc4OTExMjk0OTQ5NTQ1OTUwMTczNzk1ODMzMTk1Mjg1MzIwODgwNTUxMVxuICAxMjU0MDY5ODc0NzE1ODUyMzg2MzA1MDcxNTY5MzI5MDk2MzI5NTIyNzQ0MzA0MzU1N1xuICA2Njg5NjY0ODk1MDQ0NTI0NDUyMzE2MTczMTg1NjQwMzA5ODcxMTEyMTcyMjM4MzExM1xuICA2MjIyOTg5MzQyMzM4MDMwODEzNTMzNjI3NjYxNDI4MjgwNjQ0NDQ4NjY0NTIzODc0OVxuICAzMDM1ODkwNzI5NjI5MDQ5MTU2MDQ0MDc3MjM5MDcxMzgxMDUxNTg1OTMwNzk2MDg2NlxuICA3MDE3MjQyNzEyMTg4Mzk5ODc5NzkwODc5MjI3NDkyMTkwMTY5OTcyMDg4ODA5Mzc3NlxuICA2NTcyNzMzMzAwMTA1MzM2Nzg4MTIyMDIzNTQyMTgwOTc1MTI1NDU0MDU5NDc1MjI0M1xuICA1MjU4NDkwNzcxMTY3MDU1NjAxMzYwNDgzOTU4NjQ0NjcwNjMyNDQxNTcyMjE1NTM5N1xuICA1MzY5NzgxNzk3Nzg0NjE3NDA2NDk1NTE0OTI5MDg2MjU2OTMyMTk3ODQ2ODYyMjQ4MlxuICA4Mzk3MjI0MTM3NTY1NzA1NjA1NzQ5MDI2MTQwNzk3Mjk2ODY1MjQxNDUzNTEwMDQ3NFxuICA4MjE2NjM3MDQ4NDQwMzE5OTg5MDAwODg5NTI0MzQ1MDY1ODU0MTIyNzU4ODY2Njg4MVxuICAxNjQyNzE3MTQ3OTkyNDQ0MjkyODIzMDg2MzQ2NTY3NDgxMzkxOTEyMzE2MjgyNDU4NlxuICAxNzg2NjQ1ODM1OTEyNDU2NjUyOTQ3NjU0NTY4Mjg0ODkxMjg4MzE0MjYwNzY5MDA0MlxuICAyNDIxOTAyMjY3MTA1NTYyNjMyMTExMTEwOTM3MDU0NDIxNzUwNjk0MTY1ODk2MDQwOFxuICAwNzE5ODQwMzg1MDk2MjQ1NTQ0NDM2Mjk4MTIzMDk4Nzg3OTkyNzI0NDI4NDkwOTE4OFxuICA4NDU4MDE1NjE2NjA5NzkxOTEzMzg3NTQ5OTIwMDUyNDA2MzY4OTkxMjU2MDcxNzYwNlxuICAwNTg4NjExNjQ2NzEwOTQwNTA3NzU0MTAwMjI1Njk4MzE1NTIwMDA1NTkzNTcyOTcyNVxuICA3MTYzNjI2OTU2MTg4MjY3MDQyODI1MjQ4MzYwMDgyMzI1NzUzMDQyMDc1Mjk2MzQ1MFxuXG5GaW5kIHRoZSB0aGlydGVlbiBhZGphY2VudCBkaWdpdHMgaW4gdGhlIDEwMDAtZGlnaXQgbnVtYmVyIHRoYXQgaGF2ZSB0aGUgZ3JlYXRlc3QgcHJvZHVjdC4gV2hhdCBpcyB0aGUgdmFsdWUgb2YgdGhpcyBwcm9kdWN0P1xuXG5cIlwiXCJcblxuc3RyID0gXCJcIlwiXG4gICAgICA3MzE2NzE3NjUzMTMzMDYyNDkxOTIyNTExOTY3NDQyNjU3NDc0MjM1NTM0OTE5NDkzNFxuICAgICAgOTY5ODM1MjAzMTI3NzQ1MDYzMjYyMzk1NzgzMTgwMTY5ODQ4MDE4Njk0Nzg4NTE4NDNcbiAgICAgIDg1ODYxNTYwNzg5MTEyOTQ5NDk1NDU5NTAxNzM3OTU4MzMxOTUyODUzMjA4ODA1NTExXG4gICAgICAxMjU0MDY5ODc0NzE1ODUyMzg2MzA1MDcxNTY5MzI5MDk2MzI5NTIyNzQ0MzA0MzU1N1xuICAgICAgNjY4OTY2NDg5NTA0NDUyNDQ1MjMxNjE3MzE4NTY0MDMwOTg3MTExMjE3MjIzODMxMTNcbiAgICAgIDYyMjI5ODkzNDIzMzgwMzA4MTM1MzM2Mjc2NjE0MjgyODA2NDQ0NDg2NjQ1MjM4NzQ5XG4gICAgICAzMDM1ODkwNzI5NjI5MDQ5MTU2MDQ0MDc3MjM5MDcxMzgxMDUxNTg1OTMwNzk2MDg2NlxuICAgICAgNzAxNzI0MjcxMjE4ODM5OTg3OTc5MDg3OTIyNzQ5MjE5MDE2OTk3MjA4ODgwOTM3NzZcbiAgICAgIDY1NzI3MzMzMDAxMDUzMzY3ODgxMjIwMjM1NDIxODA5NzUxMjU0NTQwNTk0NzUyMjQzXG4gICAgICA1MjU4NDkwNzcxMTY3MDU1NjAxMzYwNDgzOTU4NjQ0NjcwNjMyNDQxNTcyMjE1NTM5N1xuICAgICAgNTM2OTc4MTc5Nzc4NDYxNzQwNjQ5NTUxNDkyOTA4NjI1NjkzMjE5Nzg0Njg2MjI0ODJcbiAgICAgIDgzOTcyMjQxMzc1NjU3MDU2MDU3NDkwMjYxNDA3OTcyOTY4NjUyNDE0NTM1MTAwNDc0XG4gICAgICA4MjE2NjM3MDQ4NDQwMzE5OTg5MDAwODg5NTI0MzQ1MDY1ODU0MTIyNzU4ODY2Njg4MVxuICAgICAgMTY0MjcxNzE0Nzk5MjQ0NDI5MjgyMzA4NjM0NjU2NzQ4MTM5MTkxMjMxNjI4MjQ1ODZcbiAgICAgIDE3ODY2NDU4MzU5MTI0NTY2NTI5NDc2NTQ1NjgyODQ4OTEyODgzMTQyNjA3NjkwMDQyXG4gICAgICAyNDIxOTAyMjY3MTA1NTYyNjMyMTExMTEwOTM3MDU0NDIxNzUwNjk0MTY1ODk2MDQwOFxuICAgICAgMDcxOTg0MDM4NTA5NjI0NTU0NDQzNjI5ODEyMzA5ODc4Nzk5MjcyNDQyODQ5MDkxODhcbiAgICAgIDg0NTgwMTU2MTY2MDk3OTE5MTMzODc1NDk5MjAwNTI0MDYzNjg5OTEyNTYwNzE3NjA2XG4gICAgICAwNTg4NjExNjQ2NzEwOTQwNTA3NzU0MTAwMjI1Njk4MzE1NTIwMDA1NTkzNTcyOTcyNVxuICAgICAgNzE2MzYyNjk1NjE4ODI2NzA0MjgyNTI0ODM2MDA4MjMyNTc1MzA0MjA3NTI5NjM0NTBcbiAgICAgIFwiXCJcIlxuc3RyID0gc3RyLnJlcGxhY2UoL1teMC05XS9nbSwgXCJcIilcbmRpZ2l0cyA9IChwYXJzZUludChkaWdpdCkgZm9yIGRpZ2l0IGluIHN0cilcblxubGFyZ2VzdFByb2R1Y3QgPSAoZGlnaXRDb3VudCkgLT5cbiAgcmV0dXJuIDAgaWYgZGlnaXRDb3VudCA+IGRpZ2l0cy5sZW5ndGhcblxuICBsYXJnZXN0ID0gMFxuICBmb3Igc3RhcnQgaW4gWzAuLihkaWdpdHMubGVuZ3RoIC0gZGlnaXRDb3VudCldXG4gICAgZW5kID0gc3RhcnQgKyBkaWdpdENvdW50XG4gICAgcHJvZHVjdCA9IDFcbiAgICBmb3IgaSBpbiBbc3RhcnQuLi5lbmRdXG4gICAgICBwcm9kdWN0ICo9IGRpZ2l0c1tpXVxuICAgIGlmIGxhcmdlc3QgPCBwcm9kdWN0XG4gICAgICBsYXJnZXN0ID0gcHJvZHVjdFxuXG4gIHJldHVybiBsYXJnZXN0XG5cbnByb2JsZW0ucnVuID1cbiAgdGVzdDogLT5cbiAgICBlcXVhbChsYXJnZXN0UHJvZHVjdCg0KSwgNTgzMiwgXCJHcmVhdGVzdCBwcm9kdWN0IG9mIDQgYWRqYWNlbnQgZGlnaXRzIGlzIDU4MzJcIilcblxuICBhbnN3ZXI6IC0+XG4gICAgcmV0dXJuIGxhcmdlc3RQcm9kdWN0KDEzKVxuIiwibW9kdWxlLmV4cG9ydHMgPSBwcm9ibGVtID0gbmV3IFByb2JsZW0gXCJcIlwiXG5cblByb2JsZW0gOTogU3BlY2lhbCBQeXRoYWdvcmVhbiB0cmlwbGV0XG4tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLVxuXG5BIFB5dGhhZ29yZWFuIHRyaXBsZXQgaXMgYSBzZXQgb2YgdGhyZWUgbmF0dXJhbCBudW1iZXJzLCBhIDwgYiA8IGMsIGZvciB3aGljaCxcblxuICAgIGFeMiArIGJeMiA9IGNeMlxuXG5Gb3IgZXhhbXBsZSwgM14yICsgNF4yID0gOSArIDE2ID0gMjUgPSA1XjIuXG5cblRoZXJlIGV4aXN0cyBleGFjdGx5IG9uZSBQeXRoYWdvcmVhbiB0cmlwbGV0IGZvciB3aGljaCBhICsgYiArIGMgPSAxMDAwLlxuXG5GaW5kIHRoZSBwcm9kdWN0IGFiYy5cblxuXCJcIlwiXG5cbmlzVHJpcGxldCA9IChhLCBiLCBjKSAtPlxuICByZXR1cm4gKChhKmEpICsgKGIqYikpID09IChjKmMpXG5cbmZpbmRGaXJzdFRyaXBsZXQgPSAoc3VtKSAtPlxuICBmb3IgYSBpbiBbMS4uLjEwMDBdXG4gICAgZm9yIGIgaW4gWzEuLi4xMDAwXVxuICAgICAgYyA9IDEwMDAgLSBhIC0gYlxuICAgICAgaWYgaXNUcmlwbGV0KGEsIGIsIGMpXG4gICAgICAgIHJldHVybiBbYSwgYiwgY11cblxuICByZXR1cm4gZmFsc2VcblxuXG5wcm9ibGVtLnJ1biA9XG4gIHRlc3Q6IC0+XG4gICAgZXF1YWwoaXNUcmlwbGV0KDMsIDQsIDUpLCB0cnVlLCBcIigzLDQsNSkgaXMgYSBQeXRoYWdvcmVhbiB0cmlwbGV0XCIpXG5cbiAgYW5zd2VyOiAtPlxuICAgIHJldHVybiBmaW5kRmlyc3RUcmlwbGV0KDEwMDApXG4iLCJtb2R1bGUuZXhwb3J0cyA9IHByb2JsZW0gPSBuZXcgUHJvYmxlbSBcIlwiXCJcblxuUHJvYmxlbSAxMDogU3VtbWF0aW9uIG9mIHByaW1lc1xuLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLVxuXG5UaGUgc3VtIG9mIHRoZSBwcmltZXMgYmVsb3cgMTAgaXMgMiArIDMgKyA1ICsgNyA9IDE3LlxuXG5GaW5kIHRoZSBzdW0gb2YgYWxsIHRoZSBwcmltZXMgYmVsb3cgdHdvIG1pbGxpb24uXG5cblwiXCJcIlxuXG5wcmltZVN1bSA9IChjZWlsaW5nKSAtPlxuICBzaWV2ZSA9IG5ldyBJbmNyZW1lbnRhbFNpZXZlXG5cbiAgc3VtID0gMFxuICBsb29wXG4gICAgbiA9IHNpZXZlLm5leHQoKVxuICAgIGlmIG4gPj0gY2VpbGluZ1xuICAgICAgYnJlYWtcbiAgICBzdW0gKz0gblxuXG4gIHJldHVybiBzdW1cblxucHJvYmxlbS5ydW4gPVxuICB0ZXN0OiAtPlxuICAgIGVxdWFsKHByaW1lU3VtKDEwKSwgMTcsIFwiU3VtIG9mIHByaW1lcyBiZWxvdyAxMCBpcyAxN1wiKVxuXG4gIGFuc3dlcjogLT5cbiAgICByZXR1cm4gcHJpbWVTdW0oMjAwMDAwMClcbiIsIm1vZHVsZS5leHBvcnRzID0gcHJvYmxlbSA9IG5ldyBQcm9ibGVtIFwiXCJcIlxuXG5Qcm9ibGVtIDExOiBMYXJnZXN0IHByb2R1Y3QgaW4gYSBncmlkXG4tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tXG5cbkluIHRoZSAyMHgyMCBncmlkIGJlbG93LCBmb3VyIG51bWJlcnMgYWxvbmcgYSBkaWFnb25hbCBsaW5lIGhhdmUgYmVlbiBtYXJrZWQgaW4gcmVkLlxuXG4gICAgICAgICAgMDggMDIgMjIgOTcgMzggMTUgMDAgNDAgMDAgNzUgMDQgMDUgMDcgNzggNTIgMTIgNTAgNzcgOTEgMDhcbiAgICAgICAgICA0OSA0OSA5OSA0MCAxNyA4MSAxOCA1NyA2MCA4NyAxNyA0MCA5OCA0MyA2OSA0OCAwNCA1NiA2MiAwMFxuICAgICAgICAgIDgxIDQ5IDMxIDczIDU1IDc5IDE0IDI5IDkzIDcxIDQwIDY3IDUzIDg4IDMwIDAzIDQ5IDEzIDM2IDY1XG4gICAgICAgICAgNTIgNzAgOTUgMjMgMDQgNjAgMTEgNDIgNjkgMjQgNjggNTYgMDEgMzIgNTYgNzEgMzcgMDIgMzYgOTFcbiAgICAgICAgICAyMiAzMSAxNiA3MSA1MSA2NyA2MyA4OSA0MSA5MiAzNiA1NCAyMiA0MCA0MCAyOCA2NiAzMyAxMyA4MFxuICAgICAgICAgIDI0IDQ3IDMyIDYwIDk5IDAzIDQ1IDAyIDQ0IDc1IDMzIDUzIDc4IDM2IDg0IDIwIDM1IDE3IDEyIDUwXG4gICAgICAgICAgMzIgOTggODEgMjggNjQgMjMgNjcgMTAgMjZfMzggNDAgNjcgNTkgNTQgNzAgNjYgMTggMzggNjQgNzBcbiAgICAgICAgICA2NyAyNiAyMCA2OCAwMiA2MiAxMiAyMCA5NSA2M185NCAzOSA2MyAwOCA0MCA5MSA2NiA0OSA5NCAyMVxuICAgICAgICAgIDI0IDU1IDU4IDA1IDY2IDczIDk5IDI2IDk3IDE3IDc4Xzc4IDk2IDgzIDE0IDg4IDM0IDg5IDYzIDcyXG4gICAgICAgICAgMjEgMzYgMjMgMDkgNzUgMDAgNzYgNDQgMjAgNDUgMzUgMTQgMDAgNjEgMzMgOTcgMzQgMzEgMzMgOTVcbiAgICAgICAgICA3OCAxNyA1MyAyOCAyMiA3NSAzMSA2NyAxNSA5NCAwMyA4MCAwNCA2MiAxNiAxNCAwOSA1MyA1NiA5MlxuICAgICAgICAgIDE2IDM5IDA1IDQyIDk2IDM1IDMxIDQ3IDU1IDU4IDg4IDI0IDAwIDE3IDU0IDI0IDM2IDI5IDg1IDU3XG4gICAgICAgICAgODYgNTYgMDAgNDggMzUgNzEgODkgMDcgMDUgNDQgNDQgMzcgNDQgNjAgMjEgNTggNTEgNTQgMTcgNThcbiAgICAgICAgICAxOSA4MCA4MSA2OCAwNSA5NCA0NyA2OSAyOCA3MyA5MiAxMyA4NiA1MiAxNyA3NyAwNCA4OSA1NSA0MFxuICAgICAgICAgIDA0IDUyIDA4IDgzIDk3IDM1IDk5IDE2IDA3IDk3IDU3IDMyIDE2IDI2IDI2IDc5IDMzIDI3IDk4IDY2XG4gICAgICAgICAgODggMzYgNjggODcgNTcgNjIgMjAgNzIgMDMgNDYgMzMgNjcgNDYgNTUgMTIgMzIgNjMgOTMgNTMgNjlcbiAgICAgICAgICAwNCA0MiAxNiA3MyAzOCAyNSAzOSAxMSAyNCA5NCA3MiAxOCAwOCA0NiAyOSAzMiA0MCA2MiA3NiAzNlxuICAgICAgICAgIDIwIDY5IDM2IDQxIDcyIDMwIDIzIDg4IDM0IDYyIDk5IDY5IDgyIDY3IDU5IDg1IDc0IDA0IDM2IDE2XG4gICAgICAgICAgMjAgNzMgMzUgMjkgNzggMzEgOTAgMDEgNzQgMzEgNDkgNzEgNDggODYgODEgMTYgMjMgNTcgMDUgNTRcbiAgICAgICAgICAwMSA3MCA1NCA3MSA4MyA1MSA1NCA2OSAxNiA5MiAzMyA0OCA2MSA0MyA1MiAwMSA4OSAxOSA2NyA0OFxuXG5UaGUgcHJvZHVjdCBvZiB0aGVzZSBudW1iZXJzIGlzIDI2IHggNjMgeCA3OCB4IDE0ID0gMTc4ODY5Ni5cblxuV2hhdCBpcyB0aGUgZ3JlYXRlc3QgcHJvZHVjdCBvZiBmb3VyIGFkamFjZW50IG51bWJlcnMgaW4gdGhlIHNhbWUgZGlyZWN0aW9uICh1cCwgZG93biwgbGVmdCwgcmlnaHQsIG9yIGRpYWdvbmFsbHkpIGluIHRoZSAyMHgyMCBncmlkP1xuXG5cIlwiXCJcblxucmF3RGlnaXRzID0gXCJcIlwiXG4gIDA4IDAyIDIyIDk3IDM4IDE1IDAwIDQwIDAwIDc1IDA0IDA1IDA3IDc4IDUyIDEyIDUwIDc3IDkxIDA4XG4gIDQ5IDQ5IDk5IDQwIDE3IDgxIDE4IDU3IDYwIDg3IDE3IDQwIDk4IDQzIDY5IDQ4IDA0IDU2IDYyIDAwXG4gIDgxIDQ5IDMxIDczIDU1IDc5IDE0IDI5IDkzIDcxIDQwIDY3IDUzIDg4IDMwIDAzIDQ5IDEzIDM2IDY1XG4gIDUyIDcwIDk1IDIzIDA0IDYwIDExIDQyIDY5IDI0IDY4IDU2IDAxIDMyIDU2IDcxIDM3IDAyIDM2IDkxXG4gIDIyIDMxIDE2IDcxIDUxIDY3IDYzIDg5IDQxIDkyIDM2IDU0IDIyIDQwIDQwIDI4IDY2IDMzIDEzIDgwXG4gIDI0IDQ3IDMyIDYwIDk5IDAzIDQ1IDAyIDQ0IDc1IDMzIDUzIDc4IDM2IDg0IDIwIDM1IDE3IDEyIDUwXG4gIDMyIDk4IDgxIDI4IDY0IDIzIDY3IDEwIDI2IDM4IDQwIDY3IDU5IDU0IDcwIDY2IDE4IDM4IDY0IDcwXG4gIDY3IDI2IDIwIDY4IDAyIDYyIDEyIDIwIDk1IDYzIDk0IDM5IDYzIDA4IDQwIDkxIDY2IDQ5IDk0IDIxXG4gIDI0IDU1IDU4IDA1IDY2IDczIDk5IDI2IDk3IDE3IDc4IDc4IDk2IDgzIDE0IDg4IDM0IDg5IDYzIDcyXG4gIDIxIDM2IDIzIDA5IDc1IDAwIDc2IDQ0IDIwIDQ1IDM1IDE0IDAwIDYxIDMzIDk3IDM0IDMxIDMzIDk1XG4gIDc4IDE3IDUzIDI4IDIyIDc1IDMxIDY3IDE1IDk0IDAzIDgwIDA0IDYyIDE2IDE0IDA5IDUzIDU2IDkyXG4gIDE2IDM5IDA1IDQyIDk2IDM1IDMxIDQ3IDU1IDU4IDg4IDI0IDAwIDE3IDU0IDI0IDM2IDI5IDg1IDU3XG4gIDg2IDU2IDAwIDQ4IDM1IDcxIDg5IDA3IDA1IDQ0IDQ0IDM3IDQ0IDYwIDIxIDU4IDUxIDU0IDE3IDU4XG4gIDE5IDgwIDgxIDY4IDA1IDk0IDQ3IDY5IDI4IDczIDkyIDEzIDg2IDUyIDE3IDc3IDA0IDg5IDU1IDQwXG4gIDA0IDUyIDA4IDgzIDk3IDM1IDk5IDE2IDA3IDk3IDU3IDMyIDE2IDI2IDI2IDc5IDMzIDI3IDk4IDY2XG4gIDg4IDM2IDY4IDg3IDU3IDYyIDIwIDcyIDAzIDQ2IDMzIDY3IDQ2IDU1IDEyIDMyIDYzIDkzIDUzIDY5XG4gIDA0IDQyIDE2IDczIDM4IDI1IDM5IDExIDI0IDk0IDcyIDE4IDA4IDQ2IDI5IDMyIDQwIDYyIDc2IDM2XG4gIDIwIDY5IDM2IDQxIDcyIDMwIDIzIDg4IDM0IDYyIDk5IDY5IDgyIDY3IDU5IDg1IDc0IDA0IDM2IDE2XG4gIDIwIDczIDM1IDI5IDc4IDMxIDkwIDAxIDc0IDMxIDQ5IDcxIDQ4IDg2IDgxIDE2IDIzIDU3IDA1IDU0XG4gIDAxIDcwIDU0IDcxIDgzIDUxIDU0IDY5IDE2IDkyIDMzIDQ4IDYxIDQzIDUyIDAxIDg5IDE5IDY3IDQ4XG5cIlwiXCIucmVwbGFjZSgvW14wLTkgXS9nbSwgXCIgXCIpXG5cbmRpZ2l0cyA9IChwYXJzZUludChkaWdpdCkgZm9yIGRpZ2l0IGluIHJhd0RpZ2l0cy5zcGxpdChcIiBcIikpXG5ncmlkID0gQXJyYXkoMjApXG5mb3IgaSBpbiBbMC4uLjIwXVxuICBncmlkW2ldID0gQXJyYXkoMjApXG5cbmluZGV4ID0gMFxuZm9yIGogaW4gWzAuLi4yMF1cbiAgZm9yIGkgaW4gWzAuLi4yMF1cbiAgICBncmlkW2ldW2pdID0gZGlnaXRzW2luZGV4XVxuICAgIGluZGV4KytcblxuIyBHZXRzIGEgcHJvZHVjdCBvZiA0IHZhbHVlcyBzdGFydGluZyBhdCAoc3gsIHN5KSwgaGVhZGluZyBpbiB0aGUgZGlyZWN0aW9uIChkeCwgZHkpXG4jIFJldHVybnMgLTEgaWYgdGhlcmUgaXMgbm8gcm9vbSB0byBtYWtlIGEgc3RyaXBlIG9mIDQuXG5nZXRMaW5lUHJvZHVjdCA9IChzeCwgc3ksIGR4LCBkeSkgLT5cbiAgZXggPSBzeCArICg0ICogZHgpXG4gIHJldHVybiAtMSBpZiAoZXggPCAwKSBvciAoZXggPj0gMjApXG4gIGV5ID0gc3kgKyAoNCAqIGR5KVxuICByZXR1cm4gLTEgaWYgKGV5IDwgMCkgb3IgKGV5ID49IDIwKVxuXG4gIHggPSBzeFxuICB5ID0gc3lcbiAgcHJvZHVjdCA9IDFcbiAgZm9yIGkgaW4gWzAuLi40XVxuICAgIHByb2R1Y3QgKj0gZ3JpZFt4XVt5XVxuICAgIHggKz0gZHhcbiAgICB5ICs9IGR5XG5cbiAgcmV0dXJuIHByb2R1Y3RcblxuZ2V0TGluZSA9IChzeCwgc3ksIGR4LCBkeSkgLT5cbiAgZXggPSBzeCArICg0ICogZHgpXG4gIHJldHVybiBbXSBpZiAoZXggPCAwKSBvciAoZXggPj0gMjApXG4gIGV5ID0gc3kgKyAoNCAqIGR5KVxuICByZXR1cm4gW10gaWYgKGV5IDwgMCkgb3IgKGV5ID49IDIwKVxuXG4gIGxpbmUgPSBbXVxuXG4gIHggPSBzeFxuICB5ID0gc3lcbiAgZm9yIGkgaW4gWzAuLi40XVxuICAgIGxpbmUucHVzaCBncmlkW3hdW3ldXG4gICAgeCArPSBkeFxuICAgIHkgKz0gZHlcblxuICByZXR1cm4gbGluZVxuXG5wcm9ibGVtLnJ1biA9XG4gIHRlc3Q6IC0+XG4gICAgIyBFeGFtcGxlIGlzIGRpYWdvbmFsIHJpZ2h0L2Rvd24gZnJvbSAoOCw2KVxuICAgIG9rKHRydWUsIEpTT04uc3RyaW5naWZ5KGdldExpbmUoOCwgNiwgMSwgMSkpKVxuICAgIGVxdWFsKGdldExpbmVQcm9kdWN0KDgsIDYsIDEsIDEpLCAxNzg4Njk2LCBcIkRpYWdvbmFsIHZhbHVlIHNob3duIGluIGV4YW1wbGUgZXF1YWxzIDEsNzg4LDY5NlwiKVxuICAgIGVxdWFsKGdldExpbmVQcm9kdWN0KDQsIDgsIDEsIDApLCA0ODQ3NzMxMiwgXCJDb3JyZWN0IGFuc3dlciBpcyByaWdodCBvZiAoNCw4KSBhbmQgaGFzIHZhbHVlcyBbXVwiKVxuICAgIG9rKHRydWUsIEpTT04uc3RyaW5naWZ5KGdldExpbmUoNCwgOCwgMSwgMCkpKVxuXG4gIGFuc3dlcjogLT5cblxuICAgICMgbWF4UHJvZHVjdCA9IDFcblxuICAgIG1heCA9XG4gICAgICBwcm9kdWN0OiAxXG4gICAgICBpOiAwXG4gICAgICBqOiAwXG4gICAgICBkaXI6IFwicmlnaHRcIlxuXG4gICAgZm9yIGogaW4gWzAuLi4yMF1cbiAgICAgIGZvciBpIGluIFswLi4uMjBdXG4gICAgICAgICMgbWF4UHJvZHVjdCA9IE1hdGgubWF4KG1heFByb2R1Y3QsIGdldExpbmVQcm9kdWN0KGksIGosIDEsIDApKVxuICAgICAgICAjIG1heFByb2R1Y3QgPSBNYXRoLm1heChtYXhQcm9kdWN0LCBnZXRMaW5lUHJvZHVjdChpLCBqLCAwLCAxKSlcbiAgICAgICAgIyBtYXhQcm9kdWN0ID0gTWF0aC5tYXgobWF4UHJvZHVjdCwgZ2V0TGluZVByb2R1Y3QoaSwgaiwgMSwgMSkpXG4gICAgICAgIHAgPSBnZXRMaW5lUHJvZHVjdChpLCBqLCAxLCAwKVxuICAgICAgICBpZiBtYXgucHJvZHVjdCA8IHBcbiAgICAgICAgICBtYXgucHJvZHVjdCA9IHBcbiAgICAgICAgICBtYXguaSA9IGlcbiAgICAgICAgICBtYXguaiA9IGpcbiAgICAgICAgICBtYXguZGlyID0gXCJyaWdodFwiXG4gICAgICAgICAgaWYgcCA9PSA0ODQ3NzMxMlxuICAgICAgICAgICAgY29uc29sZS5sb2cgXCJ3YXRcIlxuICAgICAgICAgICAgcSA9IGdldExpbmVQcm9kdWN0KGksIGosIDEsIDApXG4gICAgICAgICAgICBjb25zb2xlLmxvZyBxXG4gICAgICAgIHAgPSBnZXRMaW5lUHJvZHVjdChpLCBqLCAwLCAxKVxuICAgICAgICBpZiBtYXgucHJvZHVjdCA8IHBcbiAgICAgICAgICBtYXgucHJvZHVjdCA9IHBcbiAgICAgICAgICBtYXguaSA9IGlcbiAgICAgICAgICBtYXguaiA9IGpcbiAgICAgICAgICBtYXguZGlyID0gXCJkb3duXCJcbiAgICAgICAgcCA9IGdldExpbmVQcm9kdWN0KGksIGosIDEsIDEpXG4gICAgICAgIGlmIG1heC5wcm9kdWN0IDwgcFxuICAgICAgICAgIG1heC5wcm9kdWN0ID0gcFxuICAgICAgICAgIG1heC5pID0gaVxuICAgICAgICAgIG1heC5qID0galxuICAgICAgICAgIG1heC5kaXIgPSBcImRpYWdvbmFsXCJcblxuICAgIHJldHVybiBtYXhcbiIsInJvb3QgPSB3aW5kb3cgIyBleHBvcnRzID8gdGhpc1xyXG5cclxuIyBTaWV2ZSB3YXMgYmxpbmRseSB0YWtlbi9hZGFwdGVkIGZyb20gUm9zZXR0YUNvZGUuIERPTlQgRVZFTiBDQVJFXHJcbmNsYXNzIEluY3JlbWVudGFsU2lldmVcclxuICBjb25zdHJ1Y3RvcjogLT5cclxuICAgIEBuID0gMFxyXG5cclxuICBuZXh0OiAtPlxyXG4gICAgQG4gKz0gMlxyXG4gICAgaWYgQG4gPCA3XHJcbiAgICAgIGlmIEBuIDwgM1xyXG4gICAgICAgIEBuID0gMVxyXG4gICAgICAgIHJldHVybiAyXHJcbiAgICAgIGlmIEBuIDwgNVxyXG4gICAgICAgIHJldHVybiAzXHJcbiAgICAgIEBkaWN0ID0ge31cclxuICAgICAgQGJwcyA9IG5ldyBJbmNyZW1lbnRhbFNpZXZlKClcclxuICAgICAgQGJwcy5uZXh0KClcclxuICAgICAgQHAgPSBAYnBzLm5leHQoKVxyXG4gICAgICBAcSA9IEBwICogQHBcclxuICAgICAgcmV0dXJuIDVcclxuICAgIGVsc2VcclxuICAgICAgcyA9IEBkaWN0W0BuXVxyXG4gICAgICBpZiBub3Qgc1xyXG4gICAgICAgIGlmIEBuIDwgQHFcclxuICAgICAgICAgIHJldHVybiBAblxyXG4gICAgICAgIGVsc2VcclxuICAgICAgICAgIHAyID0gQHAgPDwgMVxyXG4gICAgICAgICAgQGRpY3RbQG4gKyBwMl0gPSBwMlxyXG4gICAgICAgICAgQHAgPSBAYnBzLm5leHQoKVxyXG4gICAgICAgICAgQHEgPSBAcCAqIEBwXHJcbiAgICAgICAgICByZXR1cm4gQG5leHQoKVxyXG4gICAgICBlbHNlXHJcbiAgICAgICAgZGVsZXRlIEBkaWN0W0BuXVxyXG4gICAgICAgIG54dCA9IEBuICsgc1xyXG4gICAgICAgIHdoaWxlIChAZGljdFtueHRdKVxyXG4gICAgICAgICAgbnh0ICs9IHNcclxuICAgICAgICBAZGljdFtueHRdID0gc1xyXG4gICAgICAgIHJldHVybiBAbmV4dCgpXHJcblxyXG5yb290LkluY3JlbWVudGFsU2lldmUgPSBJbmNyZW1lbnRhbFNpZXZlXHJcbiIsIkxBU1RfUFJPQkxFTSA9IDExXHJcblxyXG5yb290ID0gd2luZG93ICMgZXhwb3J0cyA/IHRoaXNcclxuXHJcbnJvb3QuZXNjYXBlZFN0cmluZ2lmeSA9IChvKSAtPlxyXG4gIHN0ciA9IEpTT04uc3RyaW5naWZ5KG8pXHJcbiAgc3RyID0gc3RyLnJlcGxhY2UoXCJdXCIsIFwiXFxcXF1cIilcclxuICByZXR1cm4gc3RyXHJcblxyXG5yb290LnJ1bkFsbCA9IC0+XHJcbiAgbGFzdFB1enpsZSA9IExBU1RfUFJPQkxFTVxyXG4gIG5leHRJbmRleCA9IDBcclxuXHJcbiAgbG9hZE5leHRTY3JpcHQgPSAtPlxyXG4gICAgaWYgbmV4dEluZGV4IDwgbGFzdFB1enpsZVxyXG4gICAgICBuZXh0SW5kZXgrK1xyXG4gICAgICBydW5UZXN0KG5leHRJbmRleCwgbG9hZE5leHRTY3JpcHQpXHJcbiAgbG9hZE5leHRTY3JpcHQoKVxyXG5cclxucm9vdC5pdGVyYXRlUHJvYmxlbXMgPSAoYXJncykgLT5cclxuXHJcbiAgaW5kZXhUb1Byb2Nlc3MgPSBudWxsXHJcbiAgaWYgYXJncy5lbmRJbmRleCA+IDBcclxuICAgIGlmIGFyZ3Muc3RhcnRJbmRleCA8PSBhcmdzLmVuZEluZGV4XHJcbiAgICAgIGluZGV4VG9Qcm9jZXNzID0gYXJncy5zdGFydEluZGV4XHJcbiAgICAgIGFyZ3Muc3RhcnRJbmRleCsrXHJcbiAgZWxzZVxyXG4gICAgaWYgYXJncy5saXN0Lmxlbmd0aCA+IDBcclxuICAgICAgaW5kZXhUb1Byb2Nlc3MgPSBhcmdzLmxpc3Quc2hpZnQoKVxyXG5cclxuICBpZiBpbmRleFRvUHJvY2VzcyAhPSBudWxsXHJcbiAgICBpdGVyYXRlTmV4dCA9IC0+XHJcbiAgICAgIHdpbmRvdy5hcmdzID0gYXJnc1xyXG4gICAgICBydW5UZXN0IGluZGV4VG9Qcm9jZXNzLCAtPlxyXG4gICAgICAgIGl0ZXJhdGVQcm9ibGVtcyhhcmdzKVxyXG4gICAgaXRlcmF0ZU5leHQoKVxyXG5cclxucm9vdC5ydW5UZXN0ID0gKGluZGV4LCBjYikgLT5cclxuICBtb2R1bGVOYW1lID0gXCJlI3soJzAwMCcraW5kZXgpLnNsaWNlKC0zKX1cIlxyXG4gIHdpbmRvdy5pbmRleCA9IGluZGV4XHJcbiAgcHJvYmxlbSA9IHJlcXVpcmUobW9kdWxlTmFtZSlcclxuICBwcm9ibGVtLnByb2Nlc3MoKVxyXG4gIHdpbmRvdy5zZXRUaW1lb3V0KGNiLCAwKSBpZiBjYlxyXG5cclxuY2xhc3MgUHJvYmxlbVxyXG4gIGNvbnN0cnVjdG9yOiAoQGRlc2NyaXB0aW9uKSAtPlxyXG4gICAgQGluZGV4ID0gd2luZG93LmluZGV4XHJcbiAgICBsaW5lcyA9IEBkZXNjcmlwdGlvbi5zcGxpdCgvXFxuLylcclxuICAgIGxpbmVzLnNoaWZ0KCkgd2hpbGUgbGluZXMubGVuZ3RoID4gMCBhbmQgbGluZXNbMF0ubGVuZ3RoID09IDBcclxuICAgIEB0aXRsZSA9IGxpbmVzLnNoaWZ0KClcclxuICAgIEBsaW5lID0gbGluZXMuc2hpZnQoKVxyXG4gICAgQGRlc2NyaXB0aW9uID0gbGluZXMuam9pbihcIlxcblwiKVxyXG5cclxuICBub3c6IC0+XHJcbiAgICByZXR1cm4gaWYgd2luZG93LnBlcmZvcm1hbmNlIHRoZW4gd2luZG93LnBlcmZvcm1hbmNlLm5vdygpIGVsc2UgbmV3IERhdGUoKS5nZXRUaW1lKClcclxuXHJcbiAgcHJvY2VzczogLT5cclxuICAgIGlmIHdpbmRvdy5hcmdzLmRlc2NyaXB0aW9uXHJcbiAgICAgIHdpbmRvdy50ZXJtaW5hbC5lY2hvIFwiW1s7IzQ0NDQ0NDtdX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19dXFxuXCJcclxuXHJcbiAgICBmb3JtYXR0ZWRUaXRsZSA9ICQudGVybWluYWwuZm9ybWF0KFwiW1s7I2ZmYWEwMDtdI3tAdGl0bGV9XVwiKVxyXG4gICAgd2luZG93LnRlcm1pbmFsLmVjaG8gXCI8YSBocmVmPVxcXCI/Yz0je3dpbmRvdy5hcmdzLmNtZH0lMjAje0BpbmRleH1cXFwiPiN7Zm9ybWF0dGVkVGl0bGV9PC9hPlwiLCB7IHJhdzogdHJ1ZSB9XHJcblxyXG4gICAgaWYgd2luZG93LmFyZ3MuZGVzY3JpcHRpb25cclxuICAgICAgd2luZG93LnRlcm1pbmFsLmVjaG8gXCJbWzsjNDQ0NDQ0O10je0BsaW5lfV1cIlxyXG4gICAgICB3aW5kb3cudGVybWluYWwuZWNobyBcIltbOyNjY2NjZWU7XSN7QGRlc2NyaXB0aW9ufV1cXG5cIlxyXG5cclxuICAgIGlmIEBydW4uaGFzT3duUHJvcGVydHkgJ3Rlc3QnXHJcbiAgICAgIGFuc3dlckZ1bmMgPSBAcnVuLmFuc3dlclxyXG4gICAgICB0ZXN0RnVuYyA9IEBydW4udGVzdFxyXG4gICAgZWxzZVxyXG4gICAgICBhbnN3ZXJGdW5jID0gQHJ1blxyXG4gICAgICB0ZXN0RnVuYyA9IHVuZGVmaW5lZFxyXG5cclxuICAgIGlmIHdpbmRvdy5hcmdzLnRlc3RcclxuICAgICAgaWYgdGVzdEZ1bmMgPT0gdW5kZWZpbmVkXHJcbiAgICAgICAgd2luZG93LnRlcm1pbmFsLmVjaG8gXCJbWzsjNDQ0NDQ0O10gKG5vIHRlc3RzKV1cIlxyXG4gICAgICBlbHNlXHJcbiAgICAgICAgdGVzdEZ1bmMoKVxyXG5cclxuICAgIGlmIHdpbmRvdy5hcmdzLmFuc3dlclxyXG4gICAgICBzdGFydCA9IEBub3coKVxyXG4gICAgICBhbnN3ZXIgPSBhbnN3ZXJGdW5jKClcclxuICAgICAgZW5kID0gQG5vdygpXHJcbiAgICAgIG1zID0gZW5kIC0gc3RhcnRcclxuICAgICAgd2luZG93LnRlcm1pbmFsLmVjaG8gXCJbWzsjZmZmZmZmO10gLT4gXVtbOyNhYWZmYWE7XUFuc3dlcjpdIChbWzsjYWFmZmZmO10je21zLnRvRml4ZWQoMSl9bXNdKTogW1s7I2ZmZmZmZjtdI3tlc2NhcGVkU3RyaW5naWZ5KGFuc3dlcil9XVwiXHJcblxyXG5yb290LlByb2JsZW0gPSBQcm9ibGVtXHJcblxyXG5yb290Lm9rID0gKHYsIG1zZykgLT5cclxuICB3aW5kb3cudGVybWluYWwuZWNobyBcIltbOyNmZmZmZmY7XSAqICBdI3t2fTogI3ttc2d9XCJcclxuXHJcbnJvb3QuZXF1YWwgPSAoYSwgYiwgbXNnKSAtPlxyXG4gIGlmIGEgPT0gYlxyXG4gICAgd2luZG93LnRlcm1pbmFsLmVjaG8gXCJbWzsjZmZmZmZmO10gKiAgXVtbOyM1NTU1NTU7XVBBU1M6ICN7bXNnfV1cIlxyXG4gIGVsc2VcclxuICAgIHdpbmRvdy50ZXJtaW5hbC5lY2hvIFwiW1s7I2ZmZmZmZjtdICogIF1bWzsjZmZhYWFhO11GQUlMOiAje21zZ30gKCN7YX0gIT0gI3tifSldXCJcclxuXHJcbnJvb3Qub25Db21tYW5kID0gKGNvbW1hbmQpID0+XHJcbiAgcmV0dXJuIGlmIGNvbW1hbmQubGVuZ3RoID09IDBcclxuICBjbWQgPSAkLnRlcm1pbmFsLnBhcnNlQ29tbWFuZChjb21tYW5kKVxyXG4gIHJldHVybiBpZiBjbWQubmFtZS5sZW5ndGggPT0gMFxyXG5cclxuICBjb25zb2xlLmxvZyBjbWRcclxuXHJcbiAgdmVyYm9zZSA9IGZhbHNlXHJcblxyXG4gIGFyZ3MgPVxyXG4gICAgc3RhcnRJbmRleDogMFxyXG4gICAgZW5kSW5kZXg6IDBcclxuICAgIGxpc3Q6IFtdXHJcbiAgICBkZXNjcmlwdGlvbjogZmFsc2VcclxuICAgIHRlc3Q6IGZhbHNlXHJcbiAgICBhbnN3ZXI6IGZhbHNlXHJcblxyXG4gIHByb2Nlc3MgPSB0cnVlXHJcblxyXG4gIGZvciBhcmcgaW4gY21kLmFyZ3NcclxuICAgIGFyZyA9IFN0cmluZyhhcmcpXHJcbiAgICBjb250aW51ZSBpZiBhcmcubGVuZ3RoIDwgMVxyXG4gICAgaWYgYXJnWzBdID09ICd2J1xyXG4gICAgICB2ZXJib3NlID0gdHJ1ZVxyXG4gICAgZWxzZSBpZiBhcmcubWF0Y2goL15cXGQrJC8pXHJcbiAgICAgIHYgPSBwYXJzZUludChhcmcpXHJcbiAgICAgIGlmICh2ID49IDEpIGFuZCAodiA8PSBMQVNUX1BST0JMRU0pXHJcbiAgICAgICAgYXJncy5saXN0LnB1c2godilcclxuICAgICAgZWxzZVxyXG4gICAgICAgIHByb2Nlc3MgPSBmYWxzZVxyXG4gICAgICAgIHdpbmRvdy50ZXJtaW5hbC5lY2hvIFwiW1s7I2ZmYWFhYTtdTm8gc3VjaCB0ZXN0OiAje3Z9ICh2YWxpZCB0ZXN0cyAxLSN7TEFTVF9QUk9CTEVNfSldXCJcclxuXHJcbiAgaWYgYXJncy5saXN0Lmxlbmd0aCA9PSAwXHJcbiAgICBhcmdzLnN0YXJ0SW5kZXggPSAxXHJcbiAgICBhcmdzLmVuZEluZGV4ID0gTEFTVF9QUk9CTEVNXHJcblxyXG4gICMgU2luY2UgYWxsIG9mIG91ciBjb21tYW5kcyBoYXBwZW4gdG8gaGF2ZSB1bmlxdWUgZmlyc3QgbGV0dGVycywgbGV0IHBlb3BsZSBiZSBzdXBlciBsYXp5L3NpbGx5XHJcbiAgaWYgY21kLm5hbWVbMF0gPT0gJ2wnXHJcbiAgICBhcmdzLmNtZCA9IFwibGlzdFwiXHJcbiAgZWxzZSBpZiBjbWQubmFtZVswXSA9PSAnZCdcclxuICAgIGFyZ3MuY21kID0gXCJkZXNjcmliZVwiXHJcbiAgICBhcmdzLmRlc2NyaXB0aW9uID0gdHJ1ZVxyXG4gIGVsc2UgaWYgY21kLm5hbWVbMF0gPT0gJ3QnXHJcbiAgICBhcmdzLmNtZCA9IFwidGVzdFwiXHJcbiAgICBhcmdzLnRlc3QgPSB0cnVlXHJcbiAgZWxzZSBpZiBjbWQubmFtZVswXSA9PSAnYSdcclxuICAgIGFyZ3MuY21kID0gXCJhbnN3ZXJcIlxyXG4gICAgYXJncy5hbnN3ZXIgPSB0cnVlXHJcbiAgZWxzZSBpZiBjbWQubmFtZVswXSA9PSAncidcclxuICAgIGFyZ3MuY21kID0gXCJydW5cIlxyXG4gICAgYXJncy50ZXN0ID0gdHJ1ZVxyXG4gICAgYXJncy5hbnN3ZXIgPSB0cnVlXHJcbiAgZWxzZSBpZiBjbWQubmFtZVswXSA9PSAnZCdcclxuICAgIGFyZ3MuY21kID0gXCJkZXNjcmliZVwiXHJcbiAgICBhcmdzLmRlc2NyaXB0aW9uID0gdHJ1ZVxyXG4gIGVsc2UgaWYgY21kLm5hbWVbMF0gPT0gJ2gnXHJcbiAgICBhcmdzLmNtZCA9IFwiaGVscFwiXHJcbiAgICBwcm9jZXNzID0gZmFsc2VcclxuICAgIHdpbmRvdy50ZXJtaW5hbC5lY2hvIFwiXCJcIlxyXG4gICAgQ29tbWFuZHM6XHJcblxyXG4gICAgICAgIGxpc3QgW1hdICAgICAtIExpc3QgcHJvYmxlbSB0aXRsZXNcclxuICAgICAgICBkZXNjcmliZSBbWF0gLSBEaXNwbGF5IGZ1bGwgcHJvYmxlbSBkZXNjcmlwdGlvbnNcclxuICAgICAgICB0ZXN0IFtYXSAgICAgLSBSdW4gdW5pdCB0ZXN0c1xyXG4gICAgICAgIGFuc3dlciBbWF0gICAtIFRpbWUgYW5kIGNhbGN1bGF0ZSBhbnN3ZXJcclxuICAgICAgICBydW4gW1hdICAgICAgLSB0ZXN0IGFuZCBhbnN3ZXIgY29tYmluZWRcclxuICAgICAgICBoZWxwICAgICAgICAgLSBUaGlzIGhlbHBcclxuXHJcbiAgICAgICAgSW4gYWxsIG9mIHRoZXNlLCBbWF0gY2FuIGJlIGEgbGlzdCBvZiBvbmUgb3IgbW9yZSBwcm9ibGVtIG51bWJlcnMuIChhIHZhbHVlIGZyb20gMSB0byAje0xBU1RfUFJPQkxFTX0pLiBJZiBhYnNlbnQsIGl0IGltcGxpZXMgYWxsIHByb2JsZW1zLlxyXG4gICAgICAgIEFsc28sIGFkZGluZyB0aGUgd29yZCBcInZlcmJvc2VcIiB0byBzb21lIG9mIHRoZXNlIGNvbW1hbmRzIHdpbGwgZW1pdCB0aGUgZGVzY3JpcHRpb24gYmVmb3JlIHBlcmZvcm1pbmcgdGhlIHRhc2suXHJcblxyXG4gICAgXCJcIlwiXHJcbiAgZWxzZVxyXG4gICAgcHJvY2VzcyA9IGZhbHNlXHJcbiAgICB3aW5kb3cudGVybWluYWwuZWNobyBcIltbOyNmZmFhYWE7XVVua25vd24gY29tbWFuZC5dXCJcclxuXHJcbiAgaWYgdmVyYm9zZVxyXG4gICAgYXJncy5kZXNjcmlwdGlvbiA9IHRydWVcclxuXHJcbiAgaWYgcHJvY2Vzc1xyXG4gICAgaXRlcmF0ZVByb2JsZW1zKGFyZ3MpXHJcbiJdfQ==
