problem = new Problem """

Problem 2: Even Fibonacci numbers
---------------------------------

Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.

"""

test problem.title, ->
  fprev = 1
  fcurr = 1

  sum = 0
  while fcurr < 4000000
    if (fcurr % 2) == 0
      sum += fcurr

    fnext = fcurr + fprev
    fprev = fcurr
    fcurr = fnext

  equal(sum, 4613732, "Sum of even Fibonacci numbers <4000000: #{sum}")

  ok(true, "Answer: #{sum}")
